// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AnalyzerTest.Models;

public partial class Client
{
    [Key]
    public int ClientKey { get; set; }

    [Required]
    public string ClientName { get; set; }

    public string ReceiptHeaderHtml { get; set; }

    public string ReceiptFooterHtml { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string AuthOrgId { get; set; }

}