// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Additive_DB_Refresh.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Additive_DB_Refresh.Contexts
{
    public partial class RefreshProcessContext
    {
        private IRefreshProcessContextProcedures _procedures;

        public virtual IRefreshProcessContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new RefreshProcessContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IRefreshProcessContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class RefreshProcessContextProcedures : IRefreshProcessContextProcedures
    {
        private readonly RefreshProcessContext _context;

        public RefreshProcessContextProcedures(RefreshProcessContext context)
        {
            _context = context;
        }
    }
}
