// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class AddressType
{
    [Key]
    public int AddressTypeKey { get; set; }

    public string TypeName { get; set; }

    [InverseProperty("AddressTypeKeyNavigation")]
    public virtual ICollection<ClientLocationAddress> ClientLocationAddresses { get; set; } = new List<ClientLocationAddress>();
}