// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Keyless]
public partial class ApiUser
{
    public Guid ApiUserKey { get; set; }

    public int ClientKey { get; set; }

    [Required]
    public string ApiKey { get; set; }

    public bool IsActive { get; set; }

    [StringLength(250)]
    public string Name { get; set; }

    [ForeignKey("ClientKey")]
    public virtual Client ClientKeyNavigation { get; set; }
}