// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ApplicationObjectType
{
    [Key]
    public short ApplicationObjectTypeKey { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Description { get; set; }

    [InverseProperty("ApplicationObjectTypeKeyNavigation")]
    public virtual ICollection<ApplicationObject> ApplicationObjects { get; set; } = new List<ApplicationObject>();
}