// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("ApplicationObjectKey", "ParentObjectHierarchyKey", Name = "ix1ApplicationObjects")]
[Index("ParentObjectHierarchyKey", Name = "ix2ApplicationObjects")]
[Index("ParentObjectHierarchyKey", "ObjectHierarchyKey", "ApplicationObjectKey", Name = "ix4ApplicationObjects")]
public partial class ApplicationObject
{
    [Required]
    public HierarchyId ObjectHierarchyKey { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    public short ApplicationObjectTypeKey { get; set; }

    [Key]
    public int ApplicationObjectKey { get; set; }

    [Column("URL")]
    public string Url { get; set; }

    public HierarchyId ParentObjectHierarchyKey { get; set; }

    [ForeignKey("ApplicationObjectTypeKey")]
    [InverseProperty("ApplicationObjects")]
    public virtual ApplicationObjectType ApplicationObjectTypeKeyNavigation { get; set; }

    [InverseProperty("ApplicationObjectKeyNavigation")]
    public virtual ICollection<ClientLocationRoleApplicationObject> ClientLocationRoleApplicationObjects { get; set; } = new List<ClientLocationRoleApplicationObject>();

    [InverseProperty("ApplicationObjectKeyNavigation")]
    public virtual ICollection<System_ApplicationRolesApplicationObject> System_ApplicationRolesApplicationObjects { get; set; } = new List<System_ApplicationRolesApplicationObject>();
}