// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class AppointmentType
{
    [Key]
    public short AppointmentTypeKey { get; set; }

    [Required]
    [StringLength(50)]
    public string AppointmentTypeName { get; set; }

    [InverseProperty("AppointmentTypeKeyNavigation")]
    public virtual ICollection<EntityHierarchy> EntityHierarchies { get; set; } = new List<EntityHierarchy>();
}