// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[PrimaryKey("EntityHierarchyKey", "EntityHierarchyRateKey", "ScheduleDate", "Time")]
[Table("ScheduleRates", Schema = "avail")]
[Index("EntityHierarchyKey", "ScheduleDate", Name = "ix_avail_ScheduleRates_EH_ScheduleDate")]
[Index("EntityHierarchyKey", "ScheduleDate", "Time", Name = "ix_avail_ScheduleRates_EH_ScheduleDate_Time")]
public partial class avail_ScheduleRate
{
    [Key]
    public int EntityHierarchyKey { get; set; }

    [Key]
    public long EntityHierarchyRateKey { get; set; }

    public long ClientLocationEntityScheduleKey { get; set; }

    public int ClientLocationKey { get; set; }

    public int ClientKey { get; set; }

    public long ClientLocationEntityKey { get; set; }

    [Key]
    public DateOnly ScheduleDate { get; set; }

    [Key]
    public TimeOnly Time { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ScheduleDateTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ScheduleDateTimeEnd { get; set; }

    public short? MaxPeople { get; set; }

    public int? Duration { get; set; }

    [Column(TypeName = "money")]
    public decimal DynamicPrice { get; set; }

    [Column(TypeName = "money")]
    public decimal RegularPrice { get; set; }

    public bool IsPrivateTourRate { get; set; }

    public bool InternalUseOnly { get; set; }
}