// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[PrimaryKey("EntityHierarchyKey", "ScheduleDate", "Time", "ClientLocationResourceKey")]
[Table("ScheduleTimeResources", Schema = "avail")]
public partial class avail_ScheduleTimeResource
{
    public long ClientLocationEntityScheduleKey { get; set; }

    public int ClientLocationKey { get; set; }

    public int ClientKey { get; set; }

    public long ClientLocationEntityKey { get; set; }

    [Key]
    public long EntityHierarchyKey { get; set; }

    public int? ScheduleTimeDayResourceKey { get; set; }

    [Key]
    public DateOnly ScheduleDate { get; set; }

    [Key]
    public TimeOnly Time { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ScheduleDateTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime MinScheduleDateTimeEnd { get; set; }

    [Key]
    public int ClientLocationResourceKey { get; set; }

    public short Quantity { get; set; }

    public short? MinAssigned { get; set; }

    [ForeignKey("ClientKey")]
    [InverseProperty("avail_ScheduleTimeResources")]
    public virtual Client ClientKeyNavigation { get; set; }

    [ForeignKey("ClientLocationEntityKey")]
    [InverseProperty("avail_ScheduleTimeResources")]
    public virtual ClientLocationEntity ClientLocationEntityKeyNavigation { get; set; }

    [ForeignKey("ClientLocationEntityScheduleKey")]
    [InverseProperty("avail_ScheduleTimeResources")]
    public virtual ClientLocationEntitySchedule ClientLocationEntityScheduleKeyNavigation { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("avail_ScheduleTimeResources")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [ForeignKey("ClientLocationResourceKey")]
    [InverseProperty("avail_ScheduleTimeResources")]
    public virtual ClientLocationResource ClientLocationResourceKeyNavigation { get; set; }

    [ForeignKey("EntityHierarchyKey")]
    [InverseProperty("avail_ScheduleTimeResources")]
    public virtual EntityHierarchy EntityHierarchyKeyNavigation { get; set; }
}