// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[PrimaryKey("EntityHierarchyKey", "ScheduleDate", "Time")]
[Table("ScheduleTimes", Schema = "avail")]
public partial class avail_ScheduleTime
{
    public long ClientLocationEntityScheduleKey { get; set; }

    public int ClientLocationKey { get; set; }

    public int ClientKey { get; set; }

    public long ClientLocationEntityKey { get; set; }

    [Key]
    public long EntityHierarchyKey { get; set; }

    public long ClientLocationScheduleTimeKey { get; set; }

    public long ClientLocationScheduleTimeDayKey { get; set; }

    [Key]
    public DateOnly ScheduleDate { get; set; }

    [Key]
    public TimeOnly Time { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ScheduleDateTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime MinScheduleDateTimeEnd { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime MinScheduleDateTimeEndwInternalUse { get; set; }

    [Required]
    [StringLength(200)]
    public string Name { get; set; }

    [StringLength(250)]
    public string Description { get; set; }

    [Column("TakeAM")]
    public byte TakeAm { get; set; }

    [Column("TakePM")]
    public byte TakePm { get; set; }

    public int Length { get; set; }

    public short? RentalDuration { get; set; }

    public byte TakeTransportation { get; set; }

    public short MaxPeople { get; set; }

    [Required]
    [Column("AMPM")]
    [StringLength(2)]
    [Unicode(false)]
    public string Ampm { get; set; }

    public bool ShowSoldOutTimes { get; set; }

    public bool IsClosed { get; set; }

    public int? PickupRouteKey { get; set; }

    public short? PickupRiderCount { get; set; }

    public short? PickupMaxRiders { get; set; }

    public bool IsActive { get; set; }

    public bool HasLimitations { get; set; }

    public int? ClientLocationScheduleLimitationKey { get; set; }

    public int? ClientLocationScheduleWhenKey { get; set; }

    public bool HideAfterFirstBooking { get; set; }

    public int? HideMinutesBeforeStart { get; set; }

    public int? HideMinutesBeforeStartIfBooked { get; set; }

    public bool HideFromCustomer { get; set; }

    public bool ReleaseReservedSpaces { get; set; }

    public bool HasPickupRoute { get; set; }

    [ForeignKey("ClientLocationScheduleLimitationKey")]
    [InverseProperty("avail_ScheduleTimes")]
    public virtual ClientLocationScheduleLimitation ClientLocationScheduleLimitationKeyNavigation { get; set; }

    [ForeignKey("ClientLocationScheduleWhenKey")]
    [InverseProperty("avail_ScheduleTimes")]
    public virtual ClientLocationScheduleWhen ClientLocationScheduleWhenKeyNavigation { get; set; }

    [ForeignKey("PickupRouteKey")]
    [InverseProperty("avail_ScheduleTimes")]
    public virtual PickupRoute PickupRouteKeyNavigation { get; set; }
}