// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[PrimaryKey("EntityHierarchyKey", "ScheduleDate")]
[Table("ScheduleDays", Schema = "avail")]
public partial class avail_ScheduleDay
{
    public long ClientLocationEntityScheduleKey { get; set; }

    public int ClientLocationKey { get; set; }

    public int ClientKey { get; set; }

    public long ClientLocationEntityKey { get; set; }

    [Key]
    public long EntityHierarchyKey { get; set; }

    [Key]
    public DateOnly ScheduleDate { get; set; }

    [Required]
    [StringLength(200)]
    public string Name { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    [Column("TakeAM")]
    public byte TakeAm { get; set; }

    [Column("TakePM")]
    public byte TakePm { get; set; }

    public int Length { get; set; }

    public short? RentalDuration { get; set; }

    public byte TakeTransportation { get; set; }

    public bool ShowSoldOutTimes { get; set; }

    public bool IsOpen { get; set; }

    [ForeignKey("ClientLocationEntityKey")]
    [InverseProperty("avail_ScheduleDays")]
    public virtual ClientLocationEntity ClientLocationEntityKeyNavigation { get; set; }

    [ForeignKey("ClientLocationEntityScheduleKey")]
    [InverseProperty("avail_ScheduleDays")]
    public virtual ClientLocationEntitySchedule ClientLocationEntityScheduleKeyNavigation { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("avail_ScheduleDays")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [ForeignKey("EntityHierarchyKey")]
    [InverseProperty("avail_ScheduleDays")]
    public virtual EntityHierarchy EntityHierarchyKeyNavigation { get; set; }
}