// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class BookingAgentEntityHierarchyOptionTime
{
    [Key]
    public long BookingAgentEntityHierarchyOptionTimeKey { get; set; }

    public long BookingAgentEntityHierarchyOptionKey { get; set; }

    public TimeOnly OptionTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    [ForeignKey("BookingAgentEntityHierarchyOptionKey")]
    [InverseProperty("BookingAgentEntityHierarchyOptionTimes")]
    public virtual BookingAgentEntityHierarchyOption BookingAgentEntityHierarchyOptionKeyNavigation { get; set; }
}