// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class BookingAgentEntityHierarchyOption
{
    [Key]
    public long BookingAgentEntityHierarchyOptionKey { get; set; }

    public long BookingAgentEntityHierarchyKey { get; set; }

    public long EntityHierarchyOptionKey { get; set; }

    [Required]
    [StringLength(50)]
    public string OptionCode { get; set; }

    [StringLength(200)]
    public string OptionDescription { get; set; }

    [ForeignKey("BookingAgentEntityHierarchyKey")]
    [InverseProperty("BookingAgentEntityHierarchyOptions")]
    public virtual BookingAgentEntityHierarchy BookingAgentEntityHierarchyKeyNavigation { get; set; }

    [InverseProperty("BookingAgentEntityHierarchyOptionKeyNavigation")]
    public virtual ICollection<BookingAgentEntityHierarchyOptionTime> BookingAgentEntityHierarchyOptionTimes { get; set; } = new List<BookingAgentEntityHierarchyOptionTime>();

    [ForeignKey("EntityHierarchyOptionKey")]
    [InverseProperty("BookingAgentEntityHierarchyOptions")]
    public virtual EntityHierarchyOption EntityHierarchyOptionKeyNavigation { get; set; }
}