// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("BookingAgentBilling")]
public partial class BookingAgentBilling
{
    [Key]
    public long BookingAgentBillingKey { get; set; }

    public long BookingAgentKey { get; set; }

    public string ContactName { get; set; }

    public string EmailAddress { get; set; }

    [Required]
    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string AddressLine3 { get; set; }

    [Required]
    public string City { get; set; }

    [Required]
    public string State { get; set; }

    [Required]
    public string PostalCode { get; set; }

    public string Country { get; set; }

    public short PaymentTerms { get; set; }

    [Required]
    public string PhoneNumber { get; set; }

    public DateTime RowAdded { get; set; }

    public DateTime? DateDeleted { get; set; }

    public bool ChargeCardOnFile { get; set; }

    public long? BookingAgentCardOnFileKey { get; set; }

    public long? BookingAgentCardOnFileHistoryKey { get; set; }

    [ForeignKey("BookingAgentCardOnFileHistoryKey")]
    [InverseProperty("BookingAgentBillings")]
    public virtual History_BookingAgentCardsOnFile BookingAgentCardOnFileHistoryKeyNavigation { get; set; }

    [ForeignKey("BookingAgentCardOnFileKey")]
    [InverseProperty("BookingAgentBillings")]
    public virtual BookingAgentCardsOnFile BookingAgentCardOnFileKeyNavigation { get; set; }

    [ForeignKey("BookingAgentKey")]
    [InverseProperty("BookingAgentBillings")]
    public virtual BookingAgent BookingAgentKeyNavigation { get; set; }
}