// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class BookingAgentCommission
{
    [Key]
    public Guid BookingAgentCommissionKey { get; set; }

    public long BookingAgentKey { get; set; }

    [Column(TypeName = "numeric(25, 7)")]
    public decimal? CommissionPercent { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public short CommissionTypeKey { get; set; }

    public bool? IsCommissionOnTaxedAmount { get; set; }

    public bool? CollectsTransportCost { get; set; }

    [Column(TypeName = "numeric(25, 7)")]
    public decimal? AdultsValue { get; set; }

    [Column(TypeName = "numeric(25, 7)")]
    public decimal? ChildrenValue { get; set; }

    [Column("Old_CommissionTypeKey")]
    [StringLength(2)]
    [Unicode(false)]
    public string OldCommissionTypeKey { get; set; }

    [ForeignKey("BookingAgentKey")]
    [InverseProperty("BookingAgentCommissions")]
    public virtual BookingAgent BookingAgentKeyNavigation { get; set; }

    [ForeignKey("CommissionTypeKey")]
    [InverseProperty("BookingAgentCommissions")]
    public virtual CommissionType CommissionTypeKeyNavigation { get; set; }
}