// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("BookingAgentCardsOnFile")]
public partial class BookingAgentCardsOnFile
{
    [Key]
    public long BookingAgentCardOnFileKey { get; set; }

    public long BookingAgentKey { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string CustomerId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string CustomerCardId { get; set; }

    [Required]
    [StringLength(255)]
    public string NameOnCard { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ExpDate { get; set; }

    [Required]
    [StringLength(4)]
    [Unicode(false)]
    public string Last4 { get; set; }

    public bool HasAffiliateApproval { get; set; }

    public bool IsDefault { get; set; }

    public long AffiliateApprovalClientLoginKey { get; set; }

    public DateTime RowAdded { get; set; }

    public DateTime? DateDeleted { get; set; }

    public byte CardTypeKey { get; set; }

    [ForeignKey("AffiliateApprovalClientLoginKey")]
    [InverseProperty("BookingAgentCardsOnFiles")]
    public virtual ClientLogin AffiliateApprovalClientLoginKeyNavigation { get; set; }

    [InverseProperty("BookingAgentCardOnFileKeyNavigation")]
    public virtual ICollection<BookingAgentBilling> BookingAgentBillings { get; set; } = new List<BookingAgentBilling>();

    [ForeignKey("BookingAgentKey")]
    [InverseProperty("BookingAgentCardsOnFiles")]
    public virtual BookingAgent BookingAgentKeyNavigation { get; set; }

    [ForeignKey("CardTypeKey")]
    [InverseProperty("BookingAgentCardsOnFiles")]
    public virtual CardType CardTypeKeyNavigation { get; set; }

    [InverseProperty("BookingAgentCardOnFileKeyNavigation")]
    public virtual ICollection<History_BookingAgentCardsOnFile> History_BookingAgentCardsOnFiles { get; set; } = new List<History_BookingAgentCardsOnFile>();
}