// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class BookingAgentPackage
{
    [Key]
    public long BookingAgentPackageKey { get; set; }

    public long BookingAgentKey { get; set; }

    public Guid PackageKey { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string BookingAgentActivityId { get; set; }

    [InverseProperty("BookingAgentPackageKeyNavigation")]
    public virtual ICollection<BookingAgentEntityHierarchy> BookingAgentEntityHierarchies { get; set; } = new List<BookingAgentEntityHierarchy>();

    [ForeignKey("BookingAgentKey")]
    [InverseProperty("BookingAgentPackages")]
    public virtual BookingAgent BookingAgentKeyNavigation { get; set; }

    [ForeignKey("PackageKey")]
    [InverseProperty("BookingAgentPackages")]
    public virtual Package PackageKeyNavigation { get; set; }
}