// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("TypeName", Name = "uq_BookingAgentTypes", IsUnique = true)]
public partial class BookingAgentType
{
    [Key]
    public byte BookingAgentTypeKey { get; set; }

    [Required]
    [StringLength(50)]
    public string TypeName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    [InverseProperty("BookingAgentTypeKeyNavigation")]
    public virtual ICollection<BookingAgent> BookingAgents { get; set; } = new List<BookingAgent>();
}