// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class BookingAgentTime
{
    [Key]
    public long BookingAgentTimeKey { get; set; }

    public long BookingAgentKey { get; set; }

    public TimeOnly Time { get; set; }

    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    [ForeignKey("BookingAgentKey")]
    [InverseProperty("BookingAgentTimes")]
    public virtual BookingAgent BookingAgentKeyNavigation { get; set; }
}