// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class BookingAgentCrossSellEvent
{
    [Key]
    public int BookingAgentCrossSellEventKey { get; set; }

    public short CrossSellEventTypeKey { get; set; }

    [Column("Supplier_ClientLocationKey")]
    public int? SupplierClientLocationKey { get; set; }

    public long BookingAgentKey { get; set; }

    public DateTime RowAdded { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string Email { get; set; }

    [ForeignKey("BookingAgentKey")]
    [InverseProperty("BookingAgentCrossSellEvents")]
    public virtual BookingAgent BookingAgentKeyNavigation { get; set; }

    [ForeignKey("CrossSellEventTypeKey")]
    [InverseProperty("BookingAgentCrossSellEvents")]
    public virtual CrossSellEventType CrossSellEventTypeKeyNavigation { get; set; }

    [ForeignKey("SupplierClientLocationKey")]
    [InverseProperty("BookingAgentCrossSellEvents")]
    public virtual ClientLocation SupplierClientLocationKeyNavigation { get; set; }
}