// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("BookingAgentEntityHierarchy")]
public partial class BookingAgentEntityHierarchy
{
    [Key]
    public long BookingAgentEntityHierarchyKey { get; set; }

    public long BookingAgentKey { get; set; }

    public long EntityHierarchyKey { get; set; }

    [StringLength(100)]
    public string BookingAgentActivityId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateAdded { get; set; }

    public long? OnlineTravelAgencyKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    [StringLength(100)]
    public string ActivityLocation { get; set; }

    [StringLength(100)]
    public string DestinationCode { get; set; }

    public short? SellableMax { get; set; }

    public bool ShowInPackageOnly { get; set; }

    public short SortOrder { get; set; }

    public bool UseDynamicPricing { get; set; }

    public bool IsActive { get; set; }

    public long? BookingAgentPackageKey { get; set; }

    [StringLength(500)]
    public string BookingAgentActivityName { get; set; }

    [StringLength(2048)]
    public string BookingAgentActivityDescription { get; set; }

    [InverseProperty("BookingAgentEntityHierarchyKeyNavigation")]
    public virtual ICollection<BookingAgentEntityHierarchyOption> BookingAgentEntityHierarchyOptions { get; set; } = new List<BookingAgentEntityHierarchyOption>();

    [InverseProperty("BookingAgentEntityHierarchyKeyNavigation")]
    public virtual ICollection<BookingAgentEntityHierarchyRate> BookingAgentEntityHierarchyRates { get; set; } = new List<BookingAgentEntityHierarchyRate>();

    [ForeignKey("BookingAgentKey")]
    [InverseProperty("BookingAgentEntityHierarchies")]
    public virtual BookingAgent BookingAgentKeyNavigation { get; set; }

    [ForeignKey("BookingAgentPackageKey")]
    [InverseProperty("BookingAgentEntityHierarchies")]
    public virtual BookingAgentPackage BookingAgentPackageKeyNavigation { get; set; }

    [ForeignKey("EntityHierarchyKey")]
    [InverseProperty("BookingAgentEntityHierarchies")]
    public virtual EntityHierarchy EntityHierarchyKeyNavigation { get; set; }

    [ForeignKey("OnlineTravelAgencyKey")]
    [InverseProperty("BookingAgentEntityHierarchies")]
    public virtual OnlineTravelAgency OnlineTravelAgencyKeyNavigation { get; set; }
}