// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[PrimaryKey("ClientLocationKey", "BookingAgentKey", "Nonce")]
public partial class BookingAgentCardOnFileRequest
{
    [Key]
    public int ClientLocationKey { get; set; }

    [Key]
    public long BookingAgentKey { get; set; }

    [Key]
    [StringLength(16)]
    [Unicode(false)]
    public string Nonce { get; set; }

    public long AffiliateApprovalClientLoginKey { get; set; }

    public bool IsCompleted { get; set; }

    public DateTime RowAdded { get; set; }

    public DateTime ExpiresAt { get; set; }

    [ForeignKey("AffiliateApprovalClientLoginKey")]
    [InverseProperty("BookingAgentCardOnFileRequests")]
    public virtual ClientLogin AffiliateApprovalClientLoginKeyNavigation { get; set; }

    [ForeignKey("BookingAgentKey")]
    [InverseProperty("BookingAgentCardOnFileRequests")]
    public virtual BookingAgent BookingAgentKeyNavigation { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("BookingAgentCardOnFileRequests")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }
}