// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("CapacityTypeName", Name = "uq_CapacityTypes_CapacityTypeName", IsUnique = true)]
public partial class CapacityType
{
    [Key]
    public short CapacityTypeKey { get; set; }

    [Required]
    [StringLength(100)]
    public string CapacityTypeName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [InverseProperty("CapacityTypeKeyNavigation")]
    public virtual ICollection<EntityHierarchy> EntityHierarchies { get; set; } = new List<EntityHierarchy>();
}