// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class CardType
{
    [Key]
    public byte CardTypeKey { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Name { get; set; }

    [InverseProperty("CardTypeKeyNavigation")]
    public virtual ICollection<BookingAgentCardsOnFile> BookingAgentCardsOnFiles { get; set; } = new List<BookingAgentCardsOnFile>();
}