// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("Sessions", Schema = "CashDrawer")]
[Index("EndDate", "RegisterKey", Name = "nci_wi_Sessions_4E406D95CE88794BB42BD4988ECAF963")]
public partial class CashDrawer_Session
{
    [Key]
    public Guid SessionKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndDate { get; set; }

    public Guid RegisterKey { get; set; }

    [StringLength(250)]
    public string Description { get; set; }

    [Column(TypeName = "money")]
    public decimal StartingCash { get; set; }

    [Column(TypeName = "money")]
    public decimal? CashSales { get; set; }

    [Column(TypeName = "money")]
    public decimal? CashRefunds { get; set; }

    [Column(TypeName = "money")]
    public decimal? PayInOut { get; set; }

    [Column(TypeName = "money")]
    public decimal? EndingCash { get; set; }

    [Column(TypeName = "money")]
    public decimal? ExpectedCash { get; set; }

    [ForeignKey("RegisterKey")]
    [InverseProperty("CashDrawer_Sessions")]
    public virtual Register RegisterKeyNavigation { get; set; }
}