// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("ClientLocationRolesEntityHierarchy")]
[Index("ClientLocationRoleKey", "EntityHierarchyKey", Name = "ix1ClientLocationRolesClientLocationEntities", IsUnique = true)]
public partial class ClientLocationRolesEntityHierarchy
{
    [Key]
    public long ClientLocationRolesEntityHierarchyKey { get; set; }

    public long ClientLocationRoleKey { get; set; }

    public long EntityHierarchyKey { get; set; }

    [ForeignKey("ClientLocationRoleKey")]
    [InverseProperty("ClientLocationRolesEntityHierarchies")]
    public virtual ClientLocationRole ClientLocationRoleKeyNavigation { get; set; }

    [ForeignKey("EntityHierarchyKey")]
    [InverseProperty("ClientLocationRolesEntityHierarchies")]
    public virtual EntityHierarchy EntityHierarchyKeyNavigation { get; set; }
}