// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[PrimaryKey("ClientLocationEntityScheduleKey", "BookingAgentKey")]
public partial class ClientLocationEntityScheduleBookingAgent
{
    [Key]
    public long ClientLocationEntityScheduleKey { get; set; }

    [Key]
    public long BookingAgentKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("BookingAgentKey")]
    [InverseProperty("ClientLocationEntityScheduleBookingAgents")]
    public virtual BookingAgent BookingAgentKeyNavigation { get; set; }

    [InverseProperty("ClientLocationEntityScheduleBookingAgent")]
    public virtual ICollection<ClientLocationEntityScheduleBookingAgentRate> ClientLocationEntityScheduleBookingAgentRates { get; set; } = new List<ClientLocationEntityScheduleBookingAgentRate>();

    [ForeignKey("ClientLocationEntityScheduleKey")]
    [InverseProperty("ClientLocationEntityScheduleBookingAgents")]
    public virtual ClientLocationEntitySchedule ClientLocationEntityScheduleKeyNavigation { get; set; }

    [InverseProperty("ClientLocationEntityScheduleBookingAgent")]
    public virtual ICollection<ClientLocationScheduleTimeBookingAgent> ClientLocationScheduleTimeBookingAgents { get; set; } = new List<ClientLocationScheduleTimeBookingAgent>();
}