// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationLanguage
{
    [Key]
    public long ClientLocationLanguageKey { get; set; }

    public int ClientLocationKey { get; set; }

    public int LanguageKey { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ClientLocationLanguages")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [ForeignKey("LanguageKey")]
    [InverseProperty("ClientLocationLanguages")]
    public virtual Language LanguageKeyNavigation { get; set; }
}