// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationOtherPaymentType
{
    [Key]
    public long ClientLocationOtherPaymentTypeKey { get; set; }

    public int ClientLocationKey { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string PaymentTypeDescription { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ClientLocationOtherPaymentTypes")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }
}