// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationLogin
{
    [Key]
    public long ClientLocationLoginKey { get; set; }

    public long ClientLoginKey { get; set; }

    public int ClientLocationKey { get; set; }

    public bool DefaultLocation { get; set; }

    public bool CanGuide { get; set; }

    public bool IsDriver { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ClientLocationLogins")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [InverseProperty("ClientLocationLoginKeyNavigation")]
    public virtual ICollection<ClientLocationLoginRole> ClientLocationLoginRoles { get; set; } = new List<ClientLocationLoginRole>();

    [ForeignKey("ClientLoginKey")]
    [InverseProperty("ClientLocationLogins")]
    public virtual ClientLogin ClientLoginKeyNavigation { get; set; }
}