// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationItemDirectory
{
    [Key]
    public int ClientLocationItemDirectoryKey { get; set; }

    public int ClientLocationKey { get; set; }

    [StringLength(500)]
    public string CategoryName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PhotoVersion { get; set; }

    [StringLength(50)]
    public string PhotoRibbonText { get; set; }

    [StringLength(500)]
    public string CategoryDescription1 { get; set; }

    [StringLength(500)]
    public string CategoryDescription2 { get; set; }

    [StringLength(500)]
    public string CategoryDescription3 { get; set; }

    public int? ParentClientLocationItemDirectoryKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    public short? SortOrder { get; set; }

    public long? EntityHierarchyKey { get; set; }

    public int? ProductKey { get; set; }

    public bool? IsItem { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ClientLocationItemDirectories")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [ForeignKey("EntityHierarchyKey")]
    [InverseProperty("ClientLocationItemDirectories")]
    public virtual EntityHierarchy EntityHierarchyKeyNavigation { get; set; }

    [InverseProperty("ParentClientLocationItemDirectoryKeyNavigation")]
    public virtual ICollection<ClientLocationItemDirectory> InverseParentClientLocationItemDirectoryKeyNavigation { get; set; } = new List<ClientLocationItemDirectory>();

    [ForeignKey("ParentClientLocationItemDirectoryKey")]
    [InverseProperty("InverseParentClientLocationItemDirectoryKeyNavigation")]
    public virtual ClientLocationItemDirectory ParentClientLocationItemDirectoryKeyNavigation { get; set; }

    [ForeignKey("ProductKey")]
    [InverseProperty("ClientLocationItemDirectories")]
    public virtual Merchandise_Product ProductKeyNavigation { get; set; }
}