// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("ClientLocationScheduleTimeDayKey", "EntityHierarchyRateKey", Name = "IX_MaxParticipantsPerTime")]
[Index("ClientLocationScheduleTimeKey", Name = "IX_MaxParticipantsPerTime2")]
public partial class ClientLocationScheduleTimeDayRate
{
    [Key]
    public long ClientLocationScheduleTimeDayRateKey { get; set; }

    public int? ClientLocationScheduleTimeDayKey { get; set; }

    public long? EntityHierarchyRateKey { get; set; }

    [Column(TypeName = "decimal(19, 4)")]
    public decimal? Price { get; set; }

    public DateTime? RowAdded { get; set; }

    public bool IsHidden { get; set; }

    public short? MaxParticipantsPerTime { get; set; }

    public int ClientLocationScheduleTimeKey { get; set; }

    [ForeignKey("ClientLocationScheduleTimeKey, ClientLocationScheduleTimeDayKey")]
    [InverseProperty("ClientLocationScheduleTimeDayRates")]
    public virtual ClientLocationScheduleTimeDay ClientLocationScheduleTimeDay { get; set; }

    [InverseProperty("ClientLocationScheduleTimeDayRateKeyNavigation")]
    public virtual ICollection<ClientLocationScheduleTimeDayBookingAgentRate> ClientLocationScheduleTimeDayBookingAgentRates { get; set; } = new List<ClientLocationScheduleTimeDayBookingAgentRate>();

    [InverseProperty("ClientLocationScheduleTimeDayRateKeyNavigation")]
    public virtual ICollection<ClientLocationScheduleTimeDayOptionRate> ClientLocationScheduleTimeDayOptionRates { get; set; } = new List<ClientLocationScheduleTimeDayOptionRate>();

    [ForeignKey("ClientLocationScheduleTimeKey")]
    [InverseProperty("ClientLocationScheduleTimeDayRates")]
    public virtual ClientLocationScheduleTime ClientLocationScheduleTimeKeyNavigation { get; set; }

    [ForeignKey("EntityHierarchyRateKey")]
    [InverseProperty("ClientLocationScheduleTimeDayRates")]
    public virtual EntityHierarchyRate EntityHierarchyRateKeyNavigation { get; set; }
}