// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("ClientLocationEntityScheduleKey", "DaysOfTheWeekKey", Name = "ix_ClientLocationEntityScheduleHours_01")]
[Index("ClientLocationEntityScheduleKey", "DaysOfTheWeekKey", Name = "uq_ClientLocationEntityScheduleHours_ScheduleDaysOfTheWeek", IsUnique = true)]
public partial class ClientLocationEntityScheduleHour
{
    [Key]
    public long ClientLocationEntityScheduleHourKey { get; set; }

    public long ClientLocationEntityScheduleKey { get; set; }

    public byte DaysOfTheWeekKey { get; set; }

    public TimeOnly OpenTime { get; set; }

    public TimeOnly CloseTime { get; set; }

    [ForeignKey("ClientLocationEntityScheduleKey")]
    [InverseProperty("ClientLocationEntityScheduleHours")]
    public virtual ClientLocationEntitySchedule ClientLocationEntityScheduleKeyNavigation { get; set; }

    [ForeignKey("DaysOfTheWeekKey")]
    [InverseProperty("ClientLocationEntityScheduleHours")]
    public virtual DaysOfTheWeek DaysOfTheWeekKeyNavigation { get; set; }
}