// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationEntityPickupRoute
{
    [Key]
    public int ClientLocationEntityPickupRouteKey { get; set; }

    public long? ClientLocationEntityKey { get; set; }

    public int? PickupRouteKey { get; set; }

    [ForeignKey("ClientLocationEntityKey")]
    [InverseProperty("ClientLocationEntityPickupRoutes")]
    public virtual ClientLocationEntity ClientLocationEntityKeyNavigation { get; set; }

    [ForeignKey("PickupRouteKey")]
    [InverseProperty("ClientLocationEntityPickupRoutes")]
    public virtual PickupRoute PickupRouteKeyNavigation { get; set; }
}