// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("ClientLocationDaysOfTheWeek")]
public partial class ClientLocationDaysOfTheWeek
{
    [Key]
    public int ClientLocationDaysOfTheWeekKey { get; set; }

    public byte DaysOfTheWeekKey { get; set; }

    public long? ClientLocationEntityKey { get; set; }

    public int? ClientLocationKey { get; set; }

    [Unicode(false)]
    public string Notes { get; set; }

    [ForeignKey("ClientLocationEntityKey")]
    [InverseProperty("ClientLocationDaysOfTheWeeks")]
    public virtual ClientLocationEntity ClientLocationEntityKeyNavigation { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ClientLocationDaysOfTheWeeks")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [ForeignKey("DaysOfTheWeekKey")]
    [InverseProperty("ClientLocationDaysOfTheWeeks")]
    public virtual DaysOfTheWeek DaysOfTheWeekKeyNavigation { get; set; }
}