// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("LocationCode", Name = "UQ_PhotoLocationCode", IsUnique = true)]
[Index("ClientKey", Name = "ix2ClientLocations")]
public partial class ClientLocation
{
    [Key]
    public int ClientLocationKey { get; set; }

    public int ClientKey { get; set; }

    [Required]
    [StringLength(500)]
    public string TimeZone { get; set; }

    public bool ObserveDaylightSavingTime { get; set; }

    [Required]
    public string Name { get; set; }

    public short AppointmentCompletionWindow { get; set; }

    public bool Active { get; set; }

    [StringLength(50)]
    public string PublicPhoneNumber { get; set; }

    public short? ChargeBalanceDays { get; set; }

    public string ReceiptHeaderHtml { get; set; }

    public string ReceiptFooterHtml { get; set; }

    public string ReceiptLogoBase64 { get; set; }

    [Column("SnapSportzID")]
    [StringLength(50)]
    public string SnapSportzId { get; set; }

    [Column("UTCOffset", TypeName = "datetime")]
    public DateTime Utcoffset { get; set; }

    [StringLength(50)]
    public string LocationCode { get; set; }

    [Column(TypeName = "numeric(12, 5)")]
    public decimal? TransportationTimeSlotBookingWindow { get; set; }

    public Guid? AddressKey { get; set; }

    [Required]
    public string InternalName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PhotoVersion { get; set; }

    [Column("ClientLocationGUID")]
    public Guid ClientLocationGuid { get; set; }

    public short MerchandiseCompletionWindow { get; set; }

    public string ConfirmationMessageFooter { get; set; }

    [StringLength(250)]
    public string SquareAccessToken { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SquareAccessTokenExpiresAt { get; set; }

    [StringLength(50)]
    public string SquareLocationId { get; set; }

    [Column("SquareSDKTypeKey")]
    public byte SquareSdktypeKey { get; set; }

    public byte SquareCurrencyCode { get; set; }

    public byte AdultAge { get; set; }

    public bool ConsentRequiresSignature { get; set; }

    public int CountryKey { get; set; }

    public string Website { get; set; }

    [Column("GATrackingID")]
    [StringLength(50)]
    public string GatrackingId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string LightLogoVersion { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DarkLogoVersion { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string WatermarkVersion { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string KioskBgVersion { get; set; }

    public bool AmountPaymentRequireManager { get; set; }

    public bool AmountRefundRequireManager { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string AddressLine3 { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string PostalCode { get; set; }

    public string Country { get; set; }

    public int? HotelSearchRadius { get; set; }

    public bool EnablePostVisitEmail { get; set; }

    [StringLength(50)]
    public string LocalizeJsKey { get; set; }

    [Column("FacebookPixelID")]
    [StringLength(50)]
    public string FacebookPixelId { get; set; }

    [StringLength(250)]
    public string MailChimpAccessToken { get; set; }

    [Column("MailChimpDC")]
    [StringLength(10)]
    public string MailChimpDc { get; set; }

    [StringLength(250)]
    public string MailChimpLoginUrl { get; set; }

    [StringLength(250)]
    public string MailChimpApiEndpoint { get; set; }

    public string BillingAddress { get; set; }

    public string CustomCss { get; set; }

    public string CustomJs { get; set; }

    public string GroupEmailHeader { get; set; }

    public string GroupEmailFooter { get; set; }

    public bool ShowEmailSignature { get; set; }

    public bool FeesCollectedRealtime { get; set; }

    [StringLength(250)]
    public string FacebookAccessToken { get; set; }

    public long? FacebookAccessTokenExpiresAt { get; set; }

    [Column("FacebookOfflineEventSetID")]
    [StringLength(250)]
    public string FacebookOfflineEventSetId { get; set; }

    [Column("FacebookBusinessID")]
    [StringLength(250)]
    public string FacebookBusinessId { get; set; }

    [Column("FacebookAdAccountID")]
    [StringLength(250)]
    public string FacebookAdAccountId { get; set; }

    public bool HideFeeBreakdown { get; set; }

    [Column("POSPrinterFooter")]
    public string PosprinterFooter { get; set; }

    public bool ShowInStoreToggle { get; set; }

    [Column("SojernSearchPixelID")]
    [StringLength(250)]
    public string SojernSearchPixelId { get; set; }

    [Column("SojernCartPixelID")]
    [StringLength(250)]
    public string SojernCartPixelId { get; set; }

    [Column("SojernConversionPixelID")]
    [StringLength(250)]
    public string SojernConversionPixelId { get; set; }

    public bool EnableSojern { get; set; }

    [StringLength(250)]
    public string GoogleAdConversionId { get; set; }

    [StringLength(250)]
    public string GoogleAdConversionLabelId { get; set; }

    public bool EnableGoogleAdConversions { get; set; }

    [Column(TypeName = "numeric(18, 14)")]
    public decimal? Latitude { get; set; }

    [Column(TypeName = "numeric(18, 14)")]
    public decimal? Longitude { get; set; }

    public bool UseModalForSimpleProduct { get; set; }

    [Column("TOMISSiteID")]
    [StringLength(250)]
    public string TomissiteId { get; set; }

    public bool RequireEmailOptIn { get; set; }

    public bool EnableGiftCards { get; set; }

    public bool SellGiftCardsOnline { get; set; }

    public bool MultiLocationGiftCards { get; set; }

    public string GiftCardDescription { get; set; }

    public bool DisablePromoCodes { get; set; }

    [Column("EnableTOMISChatBot")]
    public bool EnableTomischatBot { get; set; }

    public bool EnableOnlineDeposits { get; set; }

    [Column(TypeName = "money")]
    public decimal? DepositMinOrderTotal { get; set; }

    public string PackageUpgradeDescription { get; set; }

    [StringLength(250)]
    public string SquareRefreshToken { get; set; }

    [Column(TypeName = "numeric(12, 7)")]
    public decimal? DepositPercent { get; set; }

    [StringLength(250)]
    public string GoogleAccessToken { get; set; }

    [StringLength(250)]
    public string GoogleRefreshToken { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? GoogleAccessTokenExpiresAt { get; set; }

    public bool EnablePostVisitSms { get; set; }

    public bool IncludePostVisitLinkInSms { get; set; }

    public string PostVisitSmsText { get; set; }

    [StringLength(20)]
    public string SpecificCulture { get; set; }

    public bool UseItemCategories { get; set; }

    public bool UseClientLocationItemDirectories { get; set; }

    public bool HideMapFromBookingProcess { get; set; }

    [StringLength(250)]
    public string BingMarketingId { get; set; }

    public bool IsFirstNameOptional { get; set; }

    public bool IsLastNameOptional { get; set; }

    public bool IsPhoneNumberOptional { get; set; }

    public bool IsHeardAboutUsOptional { get; set; }

    public bool IsEmailOptional { get; set; }

    public bool DisableApplePayOnline { get; set; }

    public bool DisableGooglePayOnline { get; set; }

    public bool DisableTapPayments { get; set; }

    public bool EnableBingMarketing { get; set; }

    public bool CollectMailingAddressForGiftCards { get; set; }

    [StringLength(250)]
    public string ExperiencesLabel { get; set; }

    public bool AllRefundsRequireManager { get; set; }

    public bool TurnOffPasscodeForGuideAssign { get; set; }

    [StringLength(50)]
    public string MailChimpListId { get; set; }

    public bool TurnOffPasscodes { get; set; }

    [StringLength(50)]
    public string TwilioNumber { get; set; }

    public bool EnableTexting { get; set; }

    [Column("TwilioAccountSID")]
    [StringLength(50)]
    public string TwilioAccountSid { get; set; }

    [StringLength(50)]
    public string TwilioAuthToken { get; set; }

    [Column("TwilioPhoneNumberSID")]
    [StringLength(50)]
    public string TwilioPhoneNumberSid { get; set; }

    public int? InntopiaClientId { get; set; }

    public Guid? RedeamSupplierId { get; set; }

    [Column("GA4TrackingID")]
    [StringLength(50)]
    public string Ga4trackingId { get; set; }

    public string CancellationEmailHeader { get; set; }

    [Column("CollectDINInfo")]
    public bool CollectDininfo { get; set; }

    public bool EnableRentals { get; set; }

    public bool HideTipsFromGuides { get; set; }

    public bool DisableEditingPastActivity { get; set; }

    public bool EnableWaiverExpiration { get; set; }

    public short? WaiverValidMonths { get; set; }

    public bool ShowBookingTimer { get; set; }

    public bool EnableOrderLevelTransportation { get; set; }

    public string TransportRequirementsLabel { get; set; }

    public string TransportRequirements { get; set; }

    public byte BookLogoTypeKey { get; set; }

    public byte GiftCardLogoTypeKey { get; set; }

    public bool AutoAssignPickupVehicles { get; set; }

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<BookingAgentCardOnFileRequest> BookingAgentCardOnFileRequests { get; set; } = new List<BookingAgentCardOnFileRequest>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<BookingAgent> BookingAgentClientLocationKeyNavigations { get; set; } = new List<BookingAgent>();

    [InverseProperty("SupplierClientLocationKeyNavigation")]
    public virtual ICollection<BookingAgentCrossSellEvent> BookingAgentCrossSellEvents { get; set; } = new List<BookingAgentCrossSellEvent>();

    [InverseProperty("PartnerClientLocationKeyNavigation")]
    public virtual ICollection<BookingAgent> BookingAgentPartnerClientLocationKeyNavigations { get; set; } = new List<BookingAgent>();

    [ForeignKey("ClientKey")]
    [InverseProperty("ClientLocations")]
    public virtual Client ClientKeyNavigation { get; set; }

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationAddOn> ClientLocationAddOns { get; set; } = new List<ClientLocationAddOn>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationAddress> ClientLocationAddresses { get; set; } = new List<ClientLocationAddress>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationConversionTracking> ClientLocationConversionTrackings { get; set; } = new List<ClientLocationConversionTracking>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationCustomFormAssociation> ClientLocationCustomFormAssociations { get; set; } = new List<ClientLocationCustomFormAssociation>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationCustomForm> ClientLocationCustomForms { get; set; } = new List<ClientLocationCustomForm>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationDaysOfTheWeek> ClientLocationDaysOfTheWeeks { get; set; } = new List<ClientLocationDaysOfTheWeek>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationDevice> ClientLocationDevices { get; set; } = new List<ClientLocationDevice>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationDiscount> ClientLocationDiscounts { get; set; } = new List<ClientLocationDiscount>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationEmailTemplate> ClientLocationEmailTemplates { get; set; } = new List<ClientLocationEmailTemplate>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationEntity> ClientLocationEntities { get; set; } = new List<ClientLocationEntity>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationEntitySchedule> ClientLocationEntitySchedules { get; set; } = new List<ClientLocationEntitySchedule>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationHeardAboutU> ClientLocationHeardAboutUs { get; set; } = new List<ClientLocationHeardAboutU>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationItemDirectory> ClientLocationItemDirectories { get; set; } = new List<ClientLocationItemDirectory>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationLanguage> ClientLocationLanguages { get; set; } = new List<ClientLocationLanguage>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationLogin> ClientLocationLogins { get; set; } = new List<ClientLocationLogin>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationOtherPaymentType> ClientLocationOtherPaymentTypes { get; set; } = new List<ClientLocationOtherPaymentType>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationPaymentReason> ClientLocationPaymentReasons { get; set; } = new List<ClientLocationPaymentReason>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ClientLocationProcessingFee ClientLocationProcessingFee { get; set; }

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationProcessingFeeHistory> ClientLocationProcessingFeeHistories { get; set; } = new List<ClientLocationProcessingFeeHistory>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationRefundReason> ClientLocationRefundReasons { get; set; } = new List<ClientLocationRefundReason>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationResourceItem> ClientLocationResourceItems { get; set; } = new List<ClientLocationResourceItem>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationResource> ClientLocationResources { get; set; } = new List<ClientLocationResource>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationRole> ClientLocationRoles { get; set; } = new List<ClientLocationRole>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationScheduleDaysEnum> ClientLocationScheduleDaysEnums { get; set; } = new List<ClientLocationScheduleDaysEnum>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationScheduleTimeDayBookingAgentRateEnum> ClientLocationScheduleTimeDayBookingAgentRateEnums { get; set; } = new List<ClientLocationScheduleTimeDayBookingAgentRateEnum>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationTranslation> ClientLocationTranslations { get; set; } = new List<ClientLocationTranslation>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientLocationWeather> ClientLocationWeathers { get; set; } = new List<ClientLocationWeather>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientPaymentGateway> ClientPaymentGateways { get; set; } = new List<ClientPaymentGateway>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ClientRefundReason> ClientRefundReasons { get; set; } = new List<ClientRefundReason>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ConsentForm> ConsentForms { get; set; } = new List<ConsentForm>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<DIN_ExperienceLevel> DIN_ExperienceLevels { get; set; } = new List<DIN_ExperienceLevel>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<DIN_Height> DIN_Heights { get; set; } = new List<DIN_Height>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<DIN_ShoeSize> DIN_ShoeSizes { get; set; } = new List<DIN_ShoeSize>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<DIN_Weight> DIN_Weights { get; set; } = new List<DIN_Weight>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<DaylightSavingTimeWindow> DaylightSavingTimeWindows { get; set; } = new List<DaylightSavingTimeWindow>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<EmailTemplate> EmailTemplates { get; set; } = new List<EmailTemplate>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<EntityHierarchy> EntityHierarchies { get; set; } = new List<EntityHierarchy>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<EntityHierarchyRateResource> EntityHierarchyRateResources { get; set; } = new List<EntityHierarchyRateResource>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<ExplicitDay> ExplicitDays { get; set; } = new List<ExplicitDay>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<FeeAssociation> FeeAssociations { get; set; } = new List<FeeAssociation>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<Fee> Fees { get; set; } = new List<Fee>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<History_DIN_ExperienceLevel> History_DIN_ExperienceLevels { get; set; } = new List<History_DIN_ExperienceLevel>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<History_DIN_Height> History_DIN_Heights { get; set; } = new List<History_DIN_Height>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<History_DIN_ShoeSize> History_DIN_ShoeSizes { get; set; } = new List<History_DIN_ShoeSize>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<History_DIN_Weight> History_DIN_Weights { get; set; } = new List<History_DIN_Weight>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<Merchandise_ProductCategory> Merchandise_ProductCategories { get; set; } = new List<Merchandise_ProductCategory>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<Merchandise_ProductCategoryAssociation> Merchandise_ProductCategoryAssociations { get; set; } = new List<Merchandise_ProductCategoryAssociation>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<Merchandise_ProductColor> Merchandise_ProductColors { get; set; } = new List<Merchandise_ProductColor>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<Merchandise_ProductRentalItem> Merchandise_ProductRentalItems { get; set; } = new List<Merchandise_ProductRentalItem>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<Merchandise_ProductSize> Merchandise_ProductSizes { get; set; } = new List<Merchandise_ProductSize>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<Merchandise_Product> Merchandise_Products { get; set; } = new List<Merchandise_Product>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<MessageTemplate> MessageTemplates { get; set; } = new List<MessageTemplate>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<OrganizationType> OrganizationTypes { get; set; } = new List<OrganizationType>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<Package> Packages { get; set; } = new List<Package>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<PickupLocation> PickupLocations { get; set; } = new List<PickupLocation>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<PickupRouteEmployee> PickupRouteEmployees { get; set; } = new List<PickupRouteEmployee>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<PickupRoute> PickupRoutes { get; set; } = new List<PickupRoute>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<PickupVehicle> PickupVehicles { get; set; } = new List<PickupVehicle>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<Register> Registers { get; set; } = new List<Register>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<avail_ScheduleDay> avail_ScheduleDays { get; set; } = new List<avail_ScheduleDay>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<avail_ScheduleRateResource> avail_ScheduleRateResources { get; set; } = new List<avail_ScheduleRateResource>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<avail_ScheduleTimeResource> avail_ScheduleTimeResources { get; set; } = new List<avail_ScheduleTimeResource>();

    [InverseProperty("ClientLocationKeyNavigation")]
    public virtual ICollection<remediate_ProcessedOrder> remediate_ProcessedOrders { get; set; } = new List<remediate_ProcessedOrder>();
}