// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("ClientPaymentGatewayKey", Name = "ix1ClientPaymentGateways")]
public partial class ClientPaymentGateway
{
    [Key]
    public int ClientPaymentGatewayKey { get; set; }

    public int ClientKey { get; set; }

    public int? ClientLocationKey { get; set; }

    public int PaymentGatewayKey { get; set; }

    [Unicode(false)]
    public string SecretApiKey { get; set; }

    [Unicode(false)]
    public string VersionNumber { get; set; }

    [Unicode(false)]
    public string DeveloperId { get; set; }

    public int? SiteId { get; set; }

    public int? LicenseId { get; set; }

    public int? DeviceId { get; set; }

    [Unicode(false)]
    public string UserName { get; set; }

    [Unicode(false)]
    public string Password { get; set; }

    public bool? IsTerminal { get; set; }

    public TimeOnly BatchCloseTime { get; set; }

    [Unicode(false)]
    public string PublicApiKey { get; set; }

    [ForeignKey("ClientKey")]
    [InverseProperty("ClientPaymentGateways")]
    public virtual Client ClientKeyNavigation { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ClientPaymentGateways")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [ForeignKey("PaymentGatewayKey")]
    [InverseProperty("ClientPaymentGateways")]
    public virtual PaymentGateway PaymentGatewayKeyNavigation { get; set; }
}