// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationResource
{
    [Key]
    public int ClientLocationResourceKey { get; set; }

    public int ClientLocationKey { get; set; }

    [Required]
    [StringLength(250)]
    public string ResourceName { get; set; }

    public int Quantity { get; set; }

    public int OutOfService { get; set; }

    public int SeatCapacityPerResource { get; set; }

    public bool UseResource { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    public int? QuantityInService { get; set; }

    public int? SeatsInService { get; set; }

    [InverseProperty("ClientLocationResourceKeyNavigation")]
    public virtual ICollection<ClientLocationEntityScheduleResource> ClientLocationEntityScheduleResources { get; set; } = new List<ClientLocationEntityScheduleResource>();

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ClientLocationResources")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [InverseProperty("ClientLocationResourceKeyNavigation")]
    public virtual ICollection<ClientLocationResourceItem> ClientLocationResourceItems { get; set; } = new List<ClientLocationResourceItem>();

    [InverseProperty("ClientLocationResourceKeyNavigation")]
    public virtual ICollection<ClientLocationScheduleTimeDayRateResource> ClientLocationScheduleTimeDayRateResources { get; set; } = new List<ClientLocationScheduleTimeDayRateResource>();

    [InverseProperty("ClientLocationResourceKeyNavigation")]
    public virtual ICollection<ClientLocationScheduleTimeDayResource> ClientLocationScheduleTimeDayResources { get; set; } = new List<ClientLocationScheduleTimeDayResource>();

    [InverseProperty("ClientLocationResourceKeyNavigation")]
    public virtual ICollection<EntityHierarchyRateResource> EntityHierarchyRateResources { get; set; } = new List<EntityHierarchyRateResource>();

    [InverseProperty("ClientLocationResourceKeyNavigation")]
    public virtual ICollection<avail_ScheduleRateResource> avail_ScheduleRateResources { get; set; } = new List<avail_ScheduleRateResource>();

    [InverseProperty("ClientLocationResourceKeyNavigation")]
    public virtual ICollection<avail_ScheduleTimeResource> avail_ScheduleTimeResources { get; set; } = new List<avail_ScheduleTimeResource>();
}