// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("ClientLocationKey", "ScheduleTypeKey", Name = "IX_ClientLocationEntitySchedules_ClientLocationKey_ScheduleTypeKey")]
[Index("ScheduleTypeKey", Name = "IX_ClientLocationEntitySchedules_ScheduleTypeKey")]
[Index("ClientLocationEntityKey", "IsDeleted", "IsScheduleTemplate", "ScheduleTypeKey", "EndDate", Name = "nci_wi_ClientLocationEntitySchedules_0E158D846B10810AAD56903225E15823")]
[Index("IsDeleted", "IsScheduleTemplate", "ScheduleTypeKey", "ClientLocationEntityKey", "EndDate", Name = "nci_wi_ClientLocationEntitySchedules_964B797CAC998EA2DCB03C81A1365A2D")]
public partial class ClientLocationEntitySchedule
{
    [Key]
    public long ClientLocationEntityScheduleKey { get; set; }

    public int ClientLocationKey { get; set; }

    public long ClientLocationEntityKey { get; set; }

    [Required]
    [StringLength(200)]
    public string Name { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    [Column("TakeAM")]
    public byte TakeAm { get; set; }

    [Column("TakePM")]
    public byte TakePm { get; set; }

    public bool IsExclusive { get; set; }

    public int Length { get; set; }

    public short? RentalDuration { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    public byte TakeTransportation { get; set; }

    public bool IsDeleted { get; set; }

    public short ScheduleTypeKey { get; set; }

    public short BookingPriority { get; set; }

    public short? MaxPeople { get; set; }

    public short? MaxAdults { get; set; }

    public short? MaxChildren { get; set; }

    public bool IsScheduleTemplate { get; set; }

    public bool HasLimitations { get; set; }

    public int? ClientLocationScheduleLimitationKey { get; set; }

    public int? ClientLocationScheduleWhenKey { get; set; }

    public int? HideMinutesBeforeStart { get; set; }

    public bool ShowSoldOutTimes { get; set; }

    public bool HideAfterFirstBooking { get; set; }

    public int? HideMinutesBeforeStartIfBooked { get; set; }

    public short? ArriveMinutesBefore { get; set; }

    public bool IsCapacityByRate { get; set; }

    [ForeignKey("ClientLocationEntityKey")]
    [InverseProperty("ClientLocationEntitySchedules")]
    public virtual ClientLocationEntity ClientLocationEntityKeyNavigation { get; set; }

    [InverseProperty("ClientLocationEntityScheduleKeyNavigation")]
    public virtual ICollection<ClientLocationEntityScheduleBookingAgent> ClientLocationEntityScheduleBookingAgents { get; set; } = new List<ClientLocationEntityScheduleBookingAgent>();

    [InverseProperty("ClientLocationEntityScheduleKeyNavigation")]
    public virtual ICollection<ClientLocationEntityScheduleHour> ClientLocationEntityScheduleHours { get; set; } = new List<ClientLocationEntityScheduleHour>();

    [InverseProperty("ClientLocationEntityScheduleKeyNavigation")]
    public virtual ICollection<ClientLocationEntityScheduleRate> ClientLocationEntityScheduleRates { get; set; } = new List<ClientLocationEntityScheduleRate>();

    [InverseProperty("ClientLocationEntityScheduleKeyNavigation")]
    public virtual ICollection<ClientLocationEntityScheduleResource> ClientLocationEntityScheduleResources { get; set; } = new List<ClientLocationEntityScheduleResource>();

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ClientLocationEntitySchedules")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [InverseProperty("ClientLocationEntityScheduleKeyNavigation")]
    public virtual ICollection<ClientLocationScheduleDaysEnum> ClientLocationScheduleDaysEnums { get; set; } = new List<ClientLocationScheduleDaysEnum>();

    [ForeignKey("ClientLocationScheduleLimitationKey")]
    [InverseProperty("ClientLocationEntitySchedules")]
    public virtual ClientLocationScheduleLimitation ClientLocationScheduleLimitationKeyNavigation { get; set; }

    [InverseProperty("ClientLocationEntityScheduleKeyNavigation")]
    public virtual ICollection<ClientLocationScheduleTimeDayBookingAgentRateEnum> ClientLocationScheduleTimeDayBookingAgentRateEnums { get; set; } = new List<ClientLocationScheduleTimeDayBookingAgentRateEnum>();

    [InverseProperty("ClientLocationEntityScheduleKeyNavigation")]
    public virtual ICollection<ClientLocationScheduleTime> ClientLocationScheduleTimes { get; set; } = new List<ClientLocationScheduleTime>();

    [ForeignKey("ClientLocationScheduleWhenKey")]
    [InverseProperty("ClientLocationEntitySchedules")]
    public virtual ClientLocationScheduleWhen ClientLocationScheduleWhenKeyNavigation { get; set; }

    [InverseProperty("ClientLocationEntityScheduleKeyNavigation")]
    public virtual ICollection<History_ClientLocationEntityScheduleRate> History_ClientLocationEntityScheduleRates { get; set; } = new List<History_ClientLocationEntityScheduleRate>();

    [ForeignKey("ScheduleTypeKey")]
    [InverseProperty("ClientLocationEntitySchedules")]
    public virtual ScheduleType ScheduleTypeKeyNavigation { get; set; }

    [InverseProperty("ClientLocationEntityScheduleKeyNavigation")]
    public virtual ICollection<avail_ScheduleDay> avail_ScheduleDays { get; set; } = new List<avail_ScheduleDay>();

    [InverseProperty("ClientLocationEntityScheduleKeyNavigation")]
    public virtual ICollection<avail_ScheduleRateResource> avail_ScheduleRateResources { get; set; } = new List<avail_ScheduleRateResource>();

    [InverseProperty("ClientLocationEntityScheduleKeyNavigation")]
    public virtual ICollection<avail_ScheduleTimeResource> avail_ScheduleTimeResources { get; set; } = new List<avail_ScheduleTimeResource>();
}