// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationScheduleTimeDayBookingAgentRate
{
    [Key]
    public long ClientLocationScheduleTimeDayBookingAgentRateKey { get; set; }

    public long ClientLocationScheduleTimeDayRateKey { get; set; }

    public long ClientLocationScheduleTimeDayBookingAgentKey { get; set; }

    public long EntityHierarchyRateKey { get; set; }

    public long BookingAgentKey { get; set; }

    public short? MaxParticipants { get; set; }

    [Column(TypeName = "numeric(9, 4)")]
    public decimal? Price { get; set; }

    [ForeignKey("BookingAgentKey")]
    [InverseProperty("ClientLocationScheduleTimeDayBookingAgentRates")]
    public virtual BookingAgent BookingAgentKeyNavigation { get; set; }

    [ForeignKey("ClientLocationScheduleTimeDayBookingAgentKey")]
    [InverseProperty("ClientLocationScheduleTimeDayBookingAgentRates")]
    public virtual ClientLocationScheduleTimeDayBookingAgent ClientLocationScheduleTimeDayBookingAgentKeyNavigation { get; set; }

    [ForeignKey("ClientLocationScheduleTimeDayRateKey")]
    [InverseProperty("ClientLocationScheduleTimeDayBookingAgentRates")]
    public virtual ClientLocationScheduleTimeDayRate ClientLocationScheduleTimeDayRateKeyNavigation { get; set; }

    [ForeignKey("EntityHierarchyRateKey")]
    [InverseProperty("ClientLocationScheduleTimeDayBookingAgentRates")]
    public virtual EntityHierarchyRate EntityHierarchyRateKeyNavigation { get; set; }
}