// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLogin
{
    [Key]
    public long ClientLoginKey { get; set; }

    public int ClientKey { get; set; }

    [Required]
    [StringLength(256)]
    [Unicode(false)]
    public string UserName { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string Password { get; set; }

    public bool Enabled { get; set; }

    public DateOnly ActiveDate { get; set; }

    public DateOnly ExpirationDate { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string Passcode { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Deleted { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Auth0Id { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string PassCodeHash { get; set; }

    [InverseProperty("AffiliateApprovalClientLoginKeyNavigation")]
    public virtual ICollection<BookingAgentCardOnFileRequest> BookingAgentCardOnFileRequests { get; set; } = new List<BookingAgentCardOnFileRequest>();

    [InverseProperty("AffiliateApprovalClientLoginKeyNavigation")]
    public virtual ICollection<BookingAgentCardsOnFile> BookingAgentCardsOnFiles { get; set; } = new List<BookingAgentCardsOnFile>();

    [InverseProperty("ClientLoginKeyNavigation")]
    public virtual ICollection<ClientEmployee> ClientEmployees { get; set; } = new List<ClientEmployee>();

    [ForeignKey("ClientKey")]
    [InverseProperty("ClientLogins")]
    public virtual Client ClientKeyNavigation { get; set; }

    [InverseProperty("ClientLoginKeyNavigation")]
    public virtual ICollection<ClientLocationLogin> ClientLocationLogins { get; set; } = new List<ClientLocationLogin>();

    [InverseProperty("ClientLoginKeyNavigation")]
    public virtual ICollection<ClientLocationScheduleTimeDayNote> ClientLocationScheduleTimeDayNotes { get; set; } = new List<ClientLocationScheduleTimeDayNote>();

    [InverseProperty("ClientLoginKeyNavigation")]
    public virtual ICollection<Merchandise_Inventory> Merchandise_Inventories { get; set; } = new List<Merchandise_Inventory>();

    [InverseProperty("ClientLoginKeyNavigation")]
    public virtual ICollection<Merchandise_ProductRentalItemNote> Merchandise_ProductRentalItemNotes { get; set; } = new List<Merchandise_ProductRentalItemNote>();

    [InverseProperty("ClientLoginKeyNavigation")]
    public virtual ICollection<Merchandise_Product> Merchandise_Products { get; set; } = new List<Merchandise_Product>();

    [InverseProperty("ClientLoginKeyNavigation")]
    public virtual ICollection<PickupRouteEmployee> PickupRouteEmployees { get; set; } = new List<PickupRouteEmployee>();
}