// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationCustomForm
{
    [Key]
    public int ClientLocationCustomFormKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    public int ClientLocationKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    [InverseProperty("ClientLocationCustomFormKeyNavigation")]
    public virtual ICollection<ClientLocationCustomField> ClientLocationCustomFields { get; set; } = new List<ClientLocationCustomField>();

    [InverseProperty("ClientLocationCustomFormKeyNavigation")]
    public virtual ICollection<ClientLocationCustomFormAssociation> ClientLocationCustomFormAssociations { get; set; } = new List<ClientLocationCustomFormAssociation>();

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ClientLocationCustomForms")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [InverseProperty("ClientLocationCustomFormKeyNavigation")]
    public virtual ICollection<History_ClientLocationCustomField> History_ClientLocationCustomFields { get; set; } = new List<History_ClientLocationCustomField>();
}