// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientAgent
{
    [Key]
    public long ClientAgentKey { get; set; }

    public int ClientKey { get; set; }

    public int AgentClientKey { get; set; }

    [Required]
    public string AgentName { get; set; }

    [Column(TypeName = "numeric(9, 5)")]
    public decimal? OrderPercentage { get; set; }

    [ForeignKey("AgentClientKey")]
    [InverseProperty("ClientAgentAgentClientKeyNavigations")]
    public virtual Client AgentClientKeyNavigation { get; set; }

    [ForeignKey("ClientKey")]
    [InverseProperty("ClientAgentClientKeyNavigations")]
    public virtual Client ClientKeyNavigation { get; set; }
}