// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("BookingAgentKey", Name = "IX_ClientLocationScheduleTimeDayOptions_BookingAgentKey")]
[Index("ClientLocationScheduleTimeDayKey", "ClientLocationScheduleTimeKey", "EntityHierarchyOptionKey", "BookingAgentKey", Name = "IX_ClientLocationScheduleTimeDayOptions_TimeDay_Time_Options_BookingAgent")]
public partial class ClientLocationScheduleTimeDayOption
{
    [Key]
    public long ClientLocationScheduleTimeDayOptionKey { get; set; }

    public int ClientLocationScheduleTimeDayKey { get; set; }

    public int ClientLocationScheduleTimeKey { get; set; }

    public long EntityHierarchyOptionKey { get; set; }

    public long BookingAgentKey { get; set; }

    public DateTime DateAdded { get; set; }

    public DateTime? DateDeleted { get; set; }

    public bool IsTimeOverride { get; set; }

    [ForeignKey("BookingAgentKey")]
    [InverseProperty("ClientLocationScheduleTimeDayOptions")]
    public virtual BookingAgent BookingAgentKeyNavigation { get; set; }

    [ForeignKey("ClientLocationScheduleTimeKey, ClientLocationScheduleTimeDayKey")]
    [InverseProperty("ClientLocationScheduleTimeDayOptions")]
    public virtual ClientLocationScheduleTimeDay ClientLocationScheduleTimeDay { get; set; }

    [InverseProperty("ClientLocationScheduleTimeDayOptionKeyNavigation")]
    public virtual ICollection<ClientLocationScheduleTimeDayOptionRate> ClientLocationScheduleTimeDayOptionRates { get; set; } = new List<ClientLocationScheduleTimeDayOptionRate>();

    [ForeignKey("EntityHierarchyOptionKey")]
    [InverseProperty("ClientLocationScheduleTimeDayOptions")]
    public virtual EntityHierarchyOption EntityHierarchyOptionKeyNavigation { get; set; }
}