// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationScheduleTimeDayNote
{
    [Key]
    public long ClientLocationScheduleTimeDayNoteKey { get; set; }

    public long EntityHierarchyKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime AppointmentDate { get; set; }

    public TimeOnly AppointmentTime { get; set; }

    public long ClientLoginKey { get; set; }

    [Required]
    public string Note { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    [ForeignKey("ClientLoginKey")]
    [InverseProperty("ClientLocationScheduleTimeDayNotes")]
    public virtual ClientLogin ClientLoginKeyNavigation { get; set; }

    [ForeignKey("EntityHierarchyKey")]
    [InverseProperty("ClientLocationScheduleTimeDayNotes")]
    public virtual EntityHierarchy EntityHierarchyKeyNavigation { get; set; }
}