// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("ClientLocationScheduleTimeDayKey", "ClientLocationResourceKey", Name = "uq_ClientLocationScheduleTimeDayResources_TimeDay_Resources", IsUnique = true)]
public partial class ClientLocationScheduleTimeDayResource
{
    [Key]
    public int ScheduleTimeDayResourceKey { get; set; }

    public int ClientLocationResourceKey { get; set; }

    public long ClientLocationEntityScheduleKey { get; set; }

    public int ClientLocationScheduleTimeKey { get; set; }

    public int ClientLocationScheduleTimeDayKey { get; set; }

    public short MaxQuantity { get; set; }

    public short? MinAssigned { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    [ForeignKey("ClientLocationResourceKey")]
    [InverseProperty("ClientLocationScheduleTimeDayResources")]
    public virtual ClientLocationResource ClientLocationResourceKeyNavigation { get; set; }

    [ForeignKey("ClientLocationScheduleTimeKey, ClientLocationScheduleTimeDayKey")]
    [InverseProperty("ClientLocationScheduleTimeDayResources")]
    public virtual ClientLocationScheduleTimeDay ClientLocationScheduleTimeDay { get; set; }
}