// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("ClientLocationKey", "ClientLocationResourceKey", "ClientLocationResourceEnum", Name = "ix_ClientLocationResourceItems_ClientLocationKey")]
[Index("ClientLocationResourceKey", "ClientLocationResourceEnum", Name = "ix_ClientLocationResourceItems_ResourceKey")]
[Index("ClientLocationResourceKey", "ClientLocationResourceEnum", Name = "uq_ClientLocationResourceItems_Enum", IsUnique = true)]
public partial class ClientLocationResourceItem
{
    [Key]
    public int ClientLocationResourceItemKey { get; set; }

    public int ClientLocationKey { get; set; }

    public int ClientLocationResourceKey { get; set; }

    public int ClientLocationResourceEnum { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ClientLocationResourceItems")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [ForeignKey("ClientLocationResourceKey")]
    [InverseProperty("ClientLocationResourceItems")]
    public virtual ClientLocationResource ClientLocationResourceKeyNavigation { get; set; }
}