// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("EntityHierarchyKey", "ClientLocationEntityKey", "Deleted", Name = "ix1ClientLocationEntities")]
[Index("ClientLocationEntityKey", "EntityHierarchyKey", "ClientLocationKey", Name = "ix2ClientLocationEntities")]
[Index("ClientLocationKey", "ClientLocationEntityKey", "EntityHierarchyKey", Name = "ix2aClientLocationEntities")]
[Index("EntityHierarchyKey", "ClientLocationKey", "HideFromTv", Name = "ix3ClientLocationEntities")]
public partial class ClientLocationEntity
{
    [Key]
    public long ClientLocationEntityKey { get; set; }

    public int ClientLocationKey { get; set; }

    public long? EntityHierarchyKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Deleted { get; set; }

    public string Message { get; set; }

    public bool WeighInRequired { get; set; }

    public string CheckInMessage { get; set; }

    public string Requirements { get; set; }

    public string NoAvailabilityMessage { get; set; }

    public short? PartialPaymentMinGroupSize { get; set; }

    public TimeOnly ScheduleCutoffWindow { get; set; }

    public bool HideFromSchedule { get; set; }

    [Column("HideFromTV")]
    public bool HideFromTv { get; set; }

    [InverseProperty("ClientLocationEntityKeyNavigation")]
    public virtual ICollection<Camera> Cameras { get; set; } = new List<Camera>();

    [InverseProperty("ClientLocationEntityKeyNavigation")]
    public virtual ICollection<ClientLocationDaysOfTheWeek> ClientLocationDaysOfTheWeeks { get; set; } = new List<ClientLocationDaysOfTheWeek>();

    [InverseProperty("ClientLocationEntityKeyNavigation")]
    public virtual ICollection<ClientLocationEntityPickupRoute> ClientLocationEntityPickupRoutes { get; set; } = new List<ClientLocationEntityPickupRoute>();

    [InverseProperty("ClientLocationEntityKeyNavigation")]
    public virtual ICollection<ClientLocationEntitySchedule> ClientLocationEntitySchedules { get; set; } = new List<ClientLocationEntitySchedule>();

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ClientLocationEntities")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [InverseProperty("ClientLocationEntityKeyNavigation")]
    public virtual ICollection<ClientLocationScheduleDaysEnum> ClientLocationScheduleDaysEnums { get; set; } = new List<ClientLocationScheduleDaysEnum>();

    [InverseProperty("ClientLocationEntityKeyNavigation")]
    public virtual ICollection<ClientLocationScheduleTimeDayBookingAgentRateEnum> ClientLocationScheduleTimeDayBookingAgentRateEnums { get; set; } = new List<ClientLocationScheduleTimeDayBookingAgentRateEnum>();

    [ForeignKey("EntityHierarchyKey")]
    [InverseProperty("ClientLocationEntities")]
    public virtual EntityHierarchy EntityHierarchyKeyNavigation { get; set; }

    [InverseProperty("ClientLocationEntityKeyNavigation")]
    public virtual ICollection<ExplicitDay> ExplicitDays { get; set; } = new List<ExplicitDay>();

    [InverseProperty("ClientLocationEntityKeyNavigation")]
    public virtual ICollection<FeeAssociation> FeeAssociations { get; set; } = new List<FeeAssociation>();

    [InverseProperty("ClientLocationEntityKeyNavigation")]
    public virtual ICollection<PhotoPackage> PhotoPackages { get; set; } = new List<PhotoPackage>();

    [InverseProperty("ClientLocationEntityKeyNavigation")]
    public virtual ICollection<avail_ScheduleDay> avail_ScheduleDays { get; set; } = new List<avail_ScheduleDay>();

    [InverseProperty("ClientLocationEntityKeyNavigation")]
    public virtual ICollection<avail_ScheduleRateResource> avail_ScheduleRateResources { get; set; } = new List<avail_ScheduleRateResource>();

    [InverseProperty("ClientLocationEntityKeyNavigation")]
    public virtual ICollection<avail_ScheduleTimeResource> avail_ScheduleTimeResources { get; set; } = new List<avail_ScheduleTimeResource>();
}