// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[PrimaryKey("ClientLocationEntityScheduleKey", "ClientLocationScheduleTimeKey", "BookingAgentKey")]
public partial class ClientLocationScheduleTimeBookingAgent
{
    [Key]
    public long ClientLocationEntityScheduleKey { get; set; }

    [Key]
    public long BookingAgentKey { get; set; }

    [Key]
    public int ClientLocationScheduleTimeKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [ForeignKey("ClientLocationEntityScheduleKey, BookingAgentKey")]
    [InverseProperty("ClientLocationScheduleTimeBookingAgents")]
    public virtual ClientLocationEntityScheduleBookingAgent ClientLocationEntityScheduleBookingAgent { get; set; }

    [InverseProperty("ClientLocationScheduleTimeBookingAgent")]
    public virtual ICollection<ClientLocationScheduleTimeDayBookingAgent> ClientLocationScheduleTimeDayBookingAgents { get; set; } = new List<ClientLocationScheduleTimeDayBookingAgent>();

    [ForeignKey("ClientLocationScheduleTimeKey")]
    [InverseProperty("ClientLocationScheduleTimeBookingAgents")]
    public virtual ClientLocationScheduleTime ClientLocationScheduleTimeKeyNavigation { get; set; }
}