// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("ClientLocationKey", "PaymentReason", Name = "ix1ClientLocationPaymentReasonKeys", IsUnique = true)]
[Index("ClientLocationKey", "Sequence", Name = "ix2ClientLocationPaymentReasonKeys", IsUnique = true)]
public partial class ClientLocationPaymentReason
{
    [Key]
    public int ClientLocationPaymentReasonKey { get; set; }

    public int ClientLocationKey { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string PaymentReason { get; set; }

    [Column("SEQUENCE")]
    public short Sequence { get; set; }

    public bool? ExcludeFromBalanceCalculations { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ClientLocationPaymentReasons")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }
}