// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationTranslation
{
    [Key]
    public long ClientLocationTranslationKey { get; set; }

    public int ClientLocationKey { get; set; }

    public int LanguageKey { get; set; }

    public string ReceiptHeaderHtml { get; set; }

    public string ReceiptFooterHtml { get; set; }

    public string GroupEmailHeader { get; set; }

    public string GroupEmailFooter { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ClientLocationTranslations")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [ForeignKey("LanguageKey")]
    [InverseProperty("ClientLocationTranslations")]
    public virtual Language LanguageKeyNavigation { get; set; }
}