// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientEmployee
{
    [Key]
    public long ClientEmployeeKey { get; set; }

    public int ClientKey { get; set; }

    public long? ClientLoginKey { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Name { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string Nickname { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(100)]
    public string FirstName { get; set; }

    [StringLength(200)]
    public string LastName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PhotoVersion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Deleted { get; set; }

    public bool CanLogin { get; set; }

    public bool InGroupSales { get; set; }

    public int? PhoneCountryKey { get; set; }

    [StringLength(20)]
    public string PhoneAreaCode { get; set; }

    [StringLength(200)]
    public string PhoneSubscriberNumber { get; set; }

    [ForeignKey("ClientKey")]
    [InverseProperty("ClientEmployees")]
    public virtual Client ClientKeyNavigation { get; set; }

    [ForeignKey("ClientLoginKey")]
    [InverseProperty("ClientEmployees")]
    public virtual ClientLogin ClientLoginKeyNavigation { get; set; }

    [InverseProperty("ClientEmployeeKeyNavigation")]
    public virtual ICollection<EntityHierarchyEmployee> EntityHierarchyEmployees { get; set; } = new List<EntityHierarchyEmployee>();
}