// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationDiscountTime
{
    [Key]
    public long ClientLocationDiscountTimeKey { get; set; }

    public long ClientLocationDiscountKey { get; set; }

    [Precision(0)]
    public TimeOnly TimeFrom { get; set; }

    [Precision(0)]
    public TimeOnly TimeTo { get; set; }

    public DateTime RowAdded { get; set; }

    public DateTime? DateDeleted { get; set; }

    [ForeignKey("ClientLocationDiscountKey")]
    [InverseProperty("ClientLocationDiscountTimes")]
    public virtual ClientLocationDiscount ClientLocationDiscountKeyNavigation { get; set; }
}