// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("ClientLocationEntityScheduleKey", "ClientLocationScheduleTimeKey", "ClientLocationScheduleTimeDayKey", "ClientLocationResourceKey", "EntityHierarchyRateKey", Name = "ix_ClientLocationScheduleTimeDayRateResources_ScheduleTimeDayResourceKey")]
[Index("ClientLocationScheduleTimeDayKey", "ClientLocationResourceKey", "EntityHierarchyRateKey", Name = "uq_ClientLocationScheduleTimeDayRateResources_TimeDayResource_Rate", IsUnique = true)]
public partial class ClientLocationScheduleTimeDayRateResource
{
    [Key]
    public int ScheduleTimeDayRateResourceKey { get; set; }

    public long EntityHierarchyRateKey { get; set; }

    public long ClientLocationEntityScheduleKey { get; set; }

    public bool UseResource { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    public int ClientLocationResourceKey { get; set; }

    public int ClientLocationScheduleTimeKey { get; set; }

    public int ClientLocationScheduleTimeDayKey { get; set; }

    public byte SortOrder { get; set; }

    [ForeignKey("ClientLocationResourceKey")]
    [InverseProperty("ClientLocationScheduleTimeDayRateResources")]
    public virtual ClientLocationResource ClientLocationResourceKeyNavigation { get; set; }

    [ForeignKey("ClientLocationScheduleTimeKey, ClientLocationScheduleTimeDayKey")]
    [InverseProperty("ClientLocationScheduleTimeDayRateResources")]
    public virtual ClientLocationScheduleTimeDay ClientLocationScheduleTimeDay { get; set; }

    [ForeignKey("EntityHierarchyRateKey")]
    [InverseProperty("ClientLocationScheduleTimeDayRateResources")]
    public virtual EntityHierarchyRate EntityHierarchyRateKeyNavigation { get; set; }
}