// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Keyless]
[Index("ClientLocationScheduleTimeDayKey", "ClientLocationScheduleTimeKey", "PickupRouteKey", Name = "uq_ClientLocationScheduleTimeDayPickupRoutes_Time_Day_Route", IsUnique = true)]
public partial class ClientLocationScheduleTimeDayPickupRoute
{
    public long ClientLocationEntityScheduleKey { get; set; }

    public int? ClientLocationScheduleTimeDayKey { get; set; }

    public int ClientLocationScheduleTimeKey { get; set; }

    public int PickupRouteKey { get; set; }

    [ForeignKey("ClientLocationScheduleTimeKey, ClientLocationScheduleTimeDayKey")]
    public virtual ClientLocationScheduleTimeDay ClientLocationScheduleTimeDay { get; set; }

    [ForeignKey("ClientLocationScheduleTimeKey")]
    public virtual ClientLocationScheduleTime ClientLocationScheduleTimeKeyNavigation { get; set; }

    [ForeignKey("PickupRouteKey")]
    public virtual PickupRoute PickupRouteKeyNavigation { get; set; }
}