// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationProductDiscount
{
    [Key]
    public int ClientLocationProductDiscountKey { get; set; }

    public long ClientLocationDiscountKey { get; set; }

    public int ProductKey { get; set; }

    [Column(TypeName = "numeric(30, 5)")]
    public decimal? Value { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("ClientLocationDiscountKey")]
    [InverseProperty("ClientLocationProductDiscounts")]
    public virtual ClientLocationDiscount ClientLocationDiscountKeyNavigation { get; set; }

    [InverseProperty("ClientLocationProductDiscountKeyNavigation")]
    public virtual ICollection<History_ClientLocationProductDiscount> History_ClientLocationProductDiscounts { get; set; } = new List<History_ClientLocationProductDiscount>();

    [ForeignKey("ProductKey")]
    [InverseProperty("ClientLocationProductDiscounts")]
    public virtual Merchandise_Product ProductKeyNavigation { get; set; }
}