// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationHeardAboutU
{
    [Key]
    public int ClientLocationHeardAboutUsKey { get; set; }

    public int ClientLocationKey { get; set; }

    [Required]
    public string Description { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    public DateOnly? EffectiveDate { get; set; }

    public DateOnly? EffectiveEndDate { get; set; }

    public bool Active { get; set; }

    public int Sequence { get; set; }

    public DateTime? DateDeleted { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ClientLocationHeardAboutUs")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }
}