// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationAddress
{
    [Key]
    public Guid ClientLocationAddressKey { get; set; }

    public int ClientLocationKey { get; set; }

    public int AddressTypeKey { get; set; }

    public Guid? AddressKey { get; set; }

    [ForeignKey("AddressTypeKey")]
    [InverseProperty("ClientLocationAddresses")]
    public virtual AddressType AddressTypeKeyNavigation { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ClientLocationAddresses")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }
}