// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationAddOn
{
    [Key]
    public Guid ClientLocationAddOnKey { get; set; }

    public int ClientLocationKey { get; set; }

    public int? ProductKey { get; set; }

    public bool IncludePhotos { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ClientLocationAddOns")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [ForeignKey("ProductKey")]
    [InverseProperty("ClientLocationAddOns")]
    public virtual Merchandise_Product ProductKeyNavigation { get; set; }
}