// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationLoginRole
{
    [Key]
    public int ClientLocationLoginRoleKey { get; set; }

    public long ClientLocationLoginKey { get; set; }

    public long ClientLocationRoleKey { get; set; }

    [ForeignKey("ClientLocationLoginKey")]
    [InverseProperty("ClientLocationLoginRoles")]
    public virtual ClientLocationLogin ClientLocationLoginKeyNavigation { get; set; }

    [ForeignKey("ClientLocationRoleKey")]
    [InverseProperty("ClientLocationLoginRoles")]
    public virtual ClientLocationRole ClientLocationRoleKeyNavigation { get; set; }
}