// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationEmailTemplate
{
    [Key]
    public Guid ClientLocationEmailTemplateKey { get; set; }

    public int ClientLocationKey { get; set; }

    public short EmailTypeKey { get; set; }

    [Required]
    [StringLength(200)]
    public string Subject { get; set; }

    [Required]
    [StringLength(500)]
    public string FromAddress { get; set; }

    [StringLength(500)]
    public string FromName { get; set; }

    [StringLength(500)]
    public string ReplyToAddress { get; set; }

    public long ClientLocationEmailTemplateKeyIdentity { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ClientLocationEmailTemplates")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [ForeignKey("EmailTypeKey")]
    [InverseProperty("ClientLocationEmailTemplates")]
    public virtual System_EmailType EmailTypeKeyNavigation { get; set; }
}