// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationScheduleLimitation
{
    [Key]
    public int ClientLocationScheduleLimitationKey { get; set; }

    [StringLength(250)]
    public string Name { get; set; }

    [InverseProperty("ClientLocationScheduleLimitationKeyNavigation")]
    public virtual ICollection<ClientLocationEntitySchedule> ClientLocationEntitySchedules { get; set; } = new List<ClientLocationEntitySchedule>();

    [InverseProperty("ClientLocationScheduleLimitationKeyNavigation")]
    public virtual ICollection<ClientLocationScheduleDaysEnum> ClientLocationScheduleDaysEnums { get; set; } = new List<ClientLocationScheduleDaysEnum>();

    [InverseProperty("ClientLocationScheduleLimitationKeyNavigation")]
    public virtual ICollection<ClientLocationScheduleTimeDay> ClientLocationScheduleTimeDays { get; set; } = new List<ClientLocationScheduleTimeDay>();

    [InverseProperty("ClientLocationScheduleLimitationKeyNavigation")]
    public virtual ICollection<avail_ScheduleTime> avail_ScheduleTimes { get; set; } = new List<avail_ScheduleTime>();
}