// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationScheduleDayBookingAgent
{
    [Key]
    public long ClientLocationScheduleDayBookingAgentKey { get; set; }

    public long ClientLocationEntityScheduleKey { get; set; }

    public DateOnly ScheduleDate { get; set; }

    public long BookingAgentKey { get; set; }

    [ForeignKey("BookingAgentKey")]
    [InverseProperty("ClientLocationScheduleDayBookingAgents")]
    public virtual BookingAgent BookingAgentKeyNavigation { get; set; }

    [ForeignKey("ClientLocationEntityScheduleKey, ScheduleDate")]
    [InverseProperty("ClientLocationScheduleDayBookingAgents")]
    public virtual ClientLocationScheduleDaysEnum ClientLocationScheduleDaysEnum { get; set; }
}