// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationRoleApplicationObject
{
    [Key]
    public long ClientLocationRoleApplicationObjectKey { get; set; }

    public long ClientLocationRoleKey { get; set; }

    public bool ReadOnly { get; set; }

    public int ApplicationObjectKey { get; set; }

    [ForeignKey("ApplicationObjectKey")]
    [InverseProperty("ClientLocationRoleApplicationObjects")]
    public virtual ApplicationObject ApplicationObjectKeyNavigation { get; set; }

    [ForeignKey("ClientLocationRoleKey")]
    [InverseProperty("ClientLocationRoleApplicationObjects")]
    public virtual ClientLocationRole ClientLocationRoleKeyNavigation { get; set; }
}