// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("ClientLocationAddOnsEntityHierarchy")]
public partial class ClientLocationAddOnsEntityHierarchy
{
    [Key]
    public Guid ClientLocationAddOnsEntityHierarchyKey { get; set; }

    public Guid ClientLocationAddOnKey { get; set; }

    public long EntityHierarchyKey { get; set; }

    [ForeignKey("EntityHierarchyKey")]
    [InverseProperty("ClientLocationAddOnsEntityHierarchies")]
    public virtual EntityHierarchy EntityHierarchyKeyNavigation { get; set; }
}