// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[PrimaryKey("ClientLocationEntityScheduleKey", "BookingAgentKey", "DaysOfTheWeekKey", "EntityHierarchyRateKey")]
public partial class ClientLocationScheduleDayBookingAgentRate
{
    [Key]
    public long ClientLocationEntityScheduleKey { get; set; }

    [Key]
    public long BookingAgentKey { get; set; }

    [Key]
    public long EntityHierarchyRateKey { get; set; }

    [Key]
    public byte DaysOfTheWeekKey { get; set; }

    [Column(TypeName = "money")]
    public decimal? Price { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    public DateOnly ScheduleDate { get; set; }

    public long? EntityHierarchyKey { get; set; }

    [ForeignKey("ClientLocationEntityScheduleKey, BookingAgentKey, EntityHierarchyRateKey")]
    [InverseProperty("ClientLocationScheduleDayBookingAgentRates")]
    public virtual ClientLocationEntityScheduleBookingAgentRate ClientLocationEntityScheduleBookingAgentRate { get; set; }

    [ForeignKey("DaysOfTheWeekKey")]
    [InverseProperty("ClientLocationScheduleDayBookingAgentRates")]
    public virtual DaysOfTheWeek DaysOfTheWeekKeyNavigation { get; set; }

    [ForeignKey("EntityHierarchyKey")]
    [InverseProperty("ClientLocationScheduleDayBookingAgentRates")]
    public virtual EntityHierarchy EntityHierarchyKeyNavigation { get; set; }
}