// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class Client
{
    [Key]
    public int ClientKey { get; set; }

    [Required]
    public string ClientName { get; set; }

    public string ReceiptHeaderHtml { get; set; }

    public string ReceiptFooterHtml { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string AuthOrgId { get; set; }

    [InverseProperty("AgentClientKeyNavigation")]
    public virtual ICollection<ClientAgent> ClientAgentAgentClientKeyNavigations { get; set; } = new List<ClientAgent>();

    [InverseProperty("ClientKeyNavigation")]
    public virtual ICollection<ClientAgent> ClientAgentClientKeyNavigations { get; set; } = new List<ClientAgent>();

    [InverseProperty("ClientKeyNavigation")]
    public virtual ICollection<ClientEmployee> ClientEmployees { get; set; } = new List<ClientEmployee>();

    [InverseProperty("ClientKeyNavigation")]
    public virtual ICollection<ClientLocationDiscount> ClientLocationDiscounts { get; set; } = new List<ClientLocationDiscount>();

    [InverseProperty("ClientKeyNavigation")]
    public virtual ICollection<ClientLocation> ClientLocations { get; set; } = new List<ClientLocation>();

    [InverseProperty("ClientKeyNavigation")]
    public virtual ICollection<ClientLogin> ClientLogins { get; set; } = new List<ClientLogin>();

    [InverseProperty("ClientKeyNavigation")]
    public virtual ICollection<ClientPaymentGateway> ClientPaymentGateways { get; set; } = new List<ClientPaymentGateway>();

    [InverseProperty("ClientKeyNavigation")]
    public virtual ICollection<ClientRefundReason> ClientRefundReasons { get; set; } = new List<ClientRefundReason>();

    [InverseProperty("ClientKeyNavigation")]
    public virtual ICollection<Merchandise_ProductCategory> Merchandise_ProductCategories { get; set; } = new List<Merchandise_ProductCategory>();

    [InverseProperty("ClientKeyNavigation")]
    public virtual ICollection<Merchandise_Product> Merchandise_Products { get; set; } = new List<Merchandise_Product>();

    [InverseProperty("ClientKeyNavigation")]
    public virtual ICollection<avail_ScheduleRateResource> avail_ScheduleRateResources { get; set; } = new List<avail_ScheduleRateResource>();

    [InverseProperty("ClientKeyNavigation")]
    public virtual ICollection<avail_ScheduleTimeResource> avail_ScheduleTimeResources { get; set; } = new List<avail_ScheduleTimeResource>();
}