// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("ClientLocationEntityScheduleKey", Name = "ix1ClientLocationScheduleTimes")]
public partial class ClientLocationScheduleTime
{
    [Key]
    public int ClientLocationScheduleTimeKey { get; set; }

    public long ClientLocationEntityScheduleKey { get; set; }

    public TimeOnly Time { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "money")]
    public decimal? AdultPriceOverride { get; set; }

    [Column(TypeName = "money")]
    public decimal? ChildPriceOverride { get; set; }

    [Column(TypeName = "money")]
    public decimal? AdultPriceNoInventoryOverride { get; set; }

    [Column(TypeName = "money")]
    public decimal? ChildPriceNoInventoryOverride { get; set; }

    [ForeignKey("ClientLocationEntityScheduleKey")]
    [InverseProperty("ClientLocationScheduleTimes")]
    public virtual ClientLocationEntitySchedule ClientLocationEntityScheduleKeyNavigation { get; set; }

    [InverseProperty("ClientLocationScheduleTimeKeyNavigation")]
    public virtual ICollection<ClientLocationScheduleTimeBookingAgent> ClientLocationScheduleTimeBookingAgents { get; set; } = new List<ClientLocationScheduleTimeBookingAgent>();

    [InverseProperty("ClientLocationScheduleTimeKeyNavigation")]
    public virtual ICollection<ClientLocationScheduleTimeDayRate> ClientLocationScheduleTimeDayRates { get; set; } = new List<ClientLocationScheduleTimeDayRate>();
}