// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationCustomField
{
    [Key]
    public int ClientLocationCustomFieldKey { get; set; }

    [StringLength(250)]
    public string CustomFieldName { get; set; }

    public string CustomFieldDesc { get; set; }

    public short ResponseTypeKey { get; set; }

    public short SortOrder { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    public bool IsRequired { get; set; }

    public bool ShowInNotes { get; set; }

    public int ClientLocationCustomFormKey { get; set; }

    public bool IsForMinor { get; set; }

    public bool ShowInWaiverParticipantList { get; set; }

    public bool ShowInConfirmationEmail { get; set; }

    [InverseProperty("ClientLocationCustomFieldKeyNavigation")]
    public virtual ICollection<ClientLocationCustomFieldResponse> ClientLocationCustomFieldResponses { get; set; } = new List<ClientLocationCustomFieldResponse>();

    [ForeignKey("ClientLocationCustomFormKey")]
    [InverseProperty("ClientLocationCustomFields")]
    public virtual ClientLocationCustomForm ClientLocationCustomFormKeyNavigation { get; set; }

    [InverseProperty("ClientLocationCustomFieldKeyNavigation")]
    public virtual ICollection<History_ClientLocationCustomFieldResponse> History_ClientLocationCustomFieldResponses { get; set; } = new List<History_ClientLocationCustomFieldResponse>();

    [InverseProperty("ClientLocationCustomFieldKeyNavigation")]
    public virtual ICollection<History_ClientLocationCustomField> History_ClientLocationCustomFields { get; set; } = new List<History_ClientLocationCustomField>();

    [ForeignKey("ResponseTypeKey")]
    [InverseProperty("ClientLocationCustomFields")]
    public virtual ResponseType ResponseTypeKeyNavigation { get; set; }
}