// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientRefundReason
{
    [Key]
    public int ClientRefundReasonKey { get; set; }

    public int ClientKey { get; set; }

    public int? ClientLocationKey { get; set; }

    [Required]
    public string Description { get; set; }

    [ForeignKey("ClientKey")]
    [InverseProperty("ClientRefundReasons")]
    public virtual Client ClientKeyNavigation { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ClientRefundReasons")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }
}