// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationCustomFieldResponse
{
    [Key]
    public int ClientLocationCustomFieldResponseKey { get; set; }

    public int ClientLocationCustomFieldKey { get; set; }

    [Required]
    public string ResponseLabel { get; set; }

    [Column("Response_Boolean")]
    public bool? ResponseBoolean { get; set; }

    public short SortOrder { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    [ForeignKey("ClientLocationCustomFieldKey")]
    [InverseProperty("ClientLocationCustomFieldResponses")]
    public virtual ClientLocationCustomField ClientLocationCustomFieldKeyNavigation { get; set; }

    [InverseProperty("ClientLocationCustomFieldResponseKeyNavigation")]
    public virtual ICollection<History_ClientLocationCustomFieldResponse> History_ClientLocationCustomFieldResponses { get; set; } = new List<History_ClientLocationCustomFieldResponse>();
}