// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationScheduleTimeDayBookingAgent
{
    public long ClientLocationEntityScheduleKey { get; set; }

    public int ClientLocationScheduleTimeKey { get; set; }

    public long BookingAgentKey { get; set; }

    public byte? DaysOfTheWeekKey { get; set; }

    [Key]
    public long ClientLocationScheduleTimeDayBookingAgentKey { get; set; }

    public bool IsClosed { get; set; }

    public short? MaxPeople { get; set; }

    public DateOnly? ScheduleDate { get; set; }

    public TimeOnly? ScheduleTime { get; set; }

    public DateTimeOffset? ScheduleDateTime { get; set; }

    [ForeignKey("ClientLocationEntityScheduleKey, ClientLocationScheduleTimeKey, BookingAgentKey")]
    [InverseProperty("ClientLocationScheduleTimeDayBookingAgents")]
    public virtual ClientLocationScheduleTimeBookingAgent ClientLocationScheduleTimeBookingAgent { get; set; }

    [InverseProperty("ClientLocationScheduleTimeDayBookingAgentKeyNavigation")]
    public virtual ICollection<ClientLocationScheduleTimeDayBookingAgentRate> ClientLocationScheduleTimeDayBookingAgentRates { get; set; } = new List<ClientLocationScheduleTimeDayBookingAgentRate>();

    [ForeignKey("DaysOfTheWeekKey")]
    [InverseProperty("ClientLocationScheduleTimeDayBookingAgents")]
    public virtual DaysOfTheWeek DaysOfTheWeekKeyNavigation { get; set; }
}