// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("ClientLocationWeather")]
public partial class ClientLocationWeather
{
    [Key]
    public long ClientLocationWeatherKey { get; set; }

    public int ClientLocationKey { get; set; }

    public TimeOnly Time { get; set; }

    [Column(TypeName = "numeric(5, 1)")]
    public decimal Temp { get; set; }

    [Required]
    [StringLength(100)]
    public string Icon { get; set; }

    [Required]
    public string IconUrl { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ClientLocationWeathers")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }
}