// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[PrimaryKey("EntityHierarchyKey", "BookingAgentKey", "ScheduleDate", "ScheduleTime", "EntityHierarchyRateKey")]
[Table("ClientLocationScheduleTimeDayBookingAgentRateEnum")]
[Index("BookingAgentKey", "ScheduleDate", Name = "IDX_ClientLocationScheduleTimeDayBookingAgentRateEnum_BookingAgentDateTimeRate")]
public partial class ClientLocationScheduleTimeDayBookingAgentRateEnum
{
    [Key]
    public long EntityHierarchyKey { get; set; }

    [Key]
    public long BookingAgentKey { get; set; }

    [Key]
    public DateOnly ScheduleDate { get; set; }

    [Key]
    public TimeOnly ScheduleTime { get; set; }

    [Key]
    public long EntityHierarchyRateKey { get; set; }

    public long ClientLocationEntityScheduleKey { get; set; }

    public int ClientLocationKey { get; set; }

    public DateTimeOffset ScheduleDateTime { get; set; }

    public long ClientLocationEntityKey { get; set; }

    [Column("Time_MaxPeople")]
    public short TimeMaxPeople { get; set; }

    [Column("Rate_MaxParticipants")]
    public short RateMaxParticipants { get; set; }

    [Column(TypeName = "money")]
    public decimal Price { get; set; }

    public bool IsClosed { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    [Column("IsTime_MaxPeopleOverridden")]
    public bool IsTimeMaxPeopleOverridden { get; set; }

    [ForeignKey("BookingAgentKey")]
    [InverseProperty("ClientLocationScheduleTimeDayBookingAgentRateEnums")]
    public virtual BookingAgent BookingAgentKeyNavigation { get; set; }

    [ForeignKey("ClientLocationEntityKey")]
    [InverseProperty("ClientLocationScheduleTimeDayBookingAgentRateEnums")]
    public virtual ClientLocationEntity ClientLocationEntityKeyNavigation { get; set; }

    [ForeignKey("ClientLocationEntityScheduleKey")]
    [InverseProperty("ClientLocationScheduleTimeDayBookingAgentRateEnums")]
    public virtual ClientLocationEntitySchedule ClientLocationEntityScheduleKeyNavigation { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ClientLocationScheduleTimeDayBookingAgentRateEnums")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [ForeignKey("EntityHierarchyKey")]
    [InverseProperty("ClientLocationScheduleTimeDayBookingAgentRateEnums")]
    public virtual EntityHierarchy EntityHierarchyKeyNavigation { get; set; }

    [ForeignKey("EntityHierarchyRateKey")]
    [InverseProperty("ClientLocationScheduleTimeDayBookingAgentRateEnums")]
    public virtual EntityHierarchyRate EntityHierarchyRateKeyNavigation { get; set; }
}