// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ClientLocationScheduleTimeDayOptionRate
{
    [Key]
    public long ClientLocationScheduleTimeDayOptionRateKey { get; set; }

    public long ClientLocationScheduleTimeDayOptionKey { get; set; }

    public long ClientLocationScheduleTimeDayRateKey { get; set; }

    [Column(TypeName = "decimal(19, 4)")]
    public decimal? Price { get; set; }

    public DateTime RowAdded { get; set; }

    public DateTime? DateDeleted { get; set; }

    public long? EntityHierarchyRateKey { get; set; }

    [ForeignKey("ClientLocationScheduleTimeDayOptionKey")]
    [InverseProperty("ClientLocationScheduleTimeDayOptionRates")]
    public virtual ClientLocationScheduleTimeDayOption ClientLocationScheduleTimeDayOptionKeyNavigation { get; set; }

    [ForeignKey("ClientLocationScheduleTimeDayRateKey")]
    [InverseProperty("ClientLocationScheduleTimeDayOptionRates")]
    public virtual ClientLocationScheduleTimeDayRate ClientLocationScheduleTimeDayRateKeyNavigation { get; set; }
}