// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("ClientLocationConversionTracking")]
public partial class ClientLocationConversionTracking
{
    [Key]
    public Guid ClientLocationConversionTrackingKey { get; set; }

    public int ClientLocationKey { get; set; }

    [Required]
    [Column("ConversionID")]
    [StringLength(50)]
    [Unicode(false)]
    public string ConversionId { get; set; }

    [Required]
    [StringLength(200)]
    public string Label { get; set; }

    [Required]
    [StringLength(10)]
    public string CurrencyCode { get; set; }

    public bool Active { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ClientLocationConversionTrackings")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }
}