// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("ClientLocationEntityHierarchyDiscountKey", "IsActive", Name = "nci_wi_ClientLocationEntityHierarchyDiscountRates_76EDBCEF84F15C7CF12EC7E1B62FB1B8")]
public partial class ClientLocationEntityHierarchyDiscountRate
{
    [Key]
    public long ClientLocationEntityHierarchyDiscountRateKey { get; set; }

    public int ClientLocationEntityHierarchyDiscountKey { get; set; }

    public long EntityHierarchyRateKey { get; set; }

    public int? MaxParticipants { get; set; }

    [Column(TypeName = "numeric(12, 9)")]
    public decimal? Value { get; set; }

    public bool IsActive { get; set; }

    public DateTime RowAdded { get; set; }

    public DateTime? Deleted { get; set; }

    [Column("Required_EntityHierarchyRateKey")]
    public long? RequiredEntityHierarchyRateKey { get; set; }

    [Column(TypeName = "numeric(9, 6)")]
    public decimal? RequiredRateRatio { get; set; }

    [ForeignKey("ClientLocationEntityHierarchyDiscountKey")]
    [InverseProperty("ClientLocationEntityHierarchyDiscountRates")]
    public virtual ClientLocationEntityHierarchyDiscount ClientLocationEntityHierarchyDiscountKeyNavigation { get; set; }

    [ForeignKey("EntityHierarchyRateKey")]
    [InverseProperty("ClientLocationEntityHierarchyDiscountRateEntityHierarchyRateKeyNavigations")]
    public virtual EntityHierarchyRate EntityHierarchyRateKeyNavigation { get; set; }

    [InverseProperty("ClientLocationEntityHierarchyDiscountRateKeyNavigation")]
    public virtual ICollection<History_ClientLocationEntityHierarchyDiscountRate> History_ClientLocationEntityHierarchyDiscountRates { get; set; } = new List<History_ClientLocationEntityHierarchyDiscountRate>();

    [ForeignKey("RequiredEntityHierarchyRateKey")]
    [InverseProperty("ClientLocationEntityHierarchyDiscountRateRequiredEntityHierarchyRateKeyNavigations")]
    public virtual EntityHierarchyRate RequiredEntityHierarchyRateKeyNavigation { get; set; }
}