// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[PrimaryKey("ClientLocationEntityScheduleKey", "ScheduleDate")]
[Table("ClientLocationScheduleDaysEnum")]
public partial class ClientLocationScheduleDaysEnum
{
    [Key]
    public long ClientLocationEntityScheduleKey { get; set; }

    public int ClientLocationKey { get; set; }

    public long ClientLocationEntityKey { get; set; }

    [Key]
    public DateOnly ScheduleDate { get; set; }

    [Required]
    [StringLength(200)]
    public string Name { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    [Column("TakeAM")]
    public byte TakeAm { get; set; }

    [Column("TakePM")]
    public byte TakePm { get; set; }

    public bool IsExclusive { get; set; }

    public int Length { get; set; }

    public short? RentalDuration { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    public byte TakeTransportation { get; set; }

    public bool IsDeleted { get; set; }

    public short ScheduleTypeKey { get; set; }

    public short BookingPriority { get; set; }

    public short? MaxPeople { get; set; }

    public bool IsScheduleTemplate { get; set; }

    public bool HasLimitations { get; set; }

    public int? ClientLocationScheduleLimitationKey { get; set; }

    public int? ClientLocationScheduleWhenKey { get; set; }

    public int? HideMinutesBeforeStart { get; set; }

    public bool ShowSoldOutTimes { get; set; }

    public bool HideAfterFirstBooking { get; set; }

    public int? HideMinutesBeforeStartIfBooked { get; set; }

    public short? ArriveMinutesBefore { get; set; }

    public bool IsCapacityByRate { get; set; }

    public bool IsChosen { get; set; }

    [ForeignKey("ClientLocationEntityKey")]
    [InverseProperty("ClientLocationScheduleDaysEnums")]
    public virtual ClientLocationEntity ClientLocationEntityKeyNavigation { get; set; }

    [ForeignKey("ClientLocationEntityScheduleKey")]
    [InverseProperty("ClientLocationScheduleDaysEnums")]
    public virtual ClientLocationEntitySchedule ClientLocationEntityScheduleKeyNavigation { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ClientLocationScheduleDaysEnums")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [InverseProperty("ClientLocationScheduleDaysEnum")]
    public virtual ICollection<ClientLocationScheduleDayBookingAgent> ClientLocationScheduleDayBookingAgents { get; set; } = new List<ClientLocationScheduleDayBookingAgent>();

    [ForeignKey("ClientLocationScheduleLimitationKey")]
    [InverseProperty("ClientLocationScheduleDaysEnums")]
    public virtual ClientLocationScheduleLimitation ClientLocationScheduleLimitationKeyNavigation { get; set; }

    [ForeignKey("ClientLocationScheduleWhenKey")]
    [InverseProperty("ClientLocationScheduleDaysEnums")]
    public virtual ClientLocationScheduleWhen ClientLocationScheduleWhenKeyNavigation { get; set; }

    [ForeignKey("ScheduleTypeKey")]
    [InverseProperty("ClientLocationScheduleDaysEnums")]
    public virtual ScheduleType ScheduleTypeKeyNavigation { get; set; }
}