// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("CommissionTypeDesc", Name = "uq_CommissionTypes_CommissionTypeDesc", IsUnique = true)]
public partial class CommissionType
{
    [Key]
    public short CommissionTypeKey { get; set; }

    [Required]
    [StringLength(50)]
    public string CommissionTypeDesc { get; set; }

    [InverseProperty("CommissionTypeKeyNavigation")]
    public virtual ICollection<BookingAgentCommission> BookingAgentCommissions { get; set; } = new List<BookingAgentCommission>();

    [InverseProperty("CommissionTypeKeyNavigation")]
    public virtual ICollection<BookingAgent> BookingAgents { get; set; } = new List<BookingAgent>();
}