// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Keyless]
public partial class ConsentFormHeading
{
    public long ConsentFormHeadingKey { get; set; }

    public int ConsentFormKey { get; set; }

    public int LanguageKey { get; set; }

    [Required]
    public string Heading { get; set; }

    [ForeignKey("ConsentFormKey")]
    public virtual ConsentForm ConsentFormKeyNavigation { get; set; }

    [ForeignKey("LanguageKey")]
    public virtual Language LanguageKeyNavigation { get; set; }
}