// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ConsentFormQuestion
{
    [Key]
    public int ConsentFormQuestionKey { get; set; }

    public int ConsentFormKey { get; set; }

    public int ConsentQuestionKey { get; set; }

    [ForeignKey("ConsentFormKey")]
    [InverseProperty("ConsentFormQuestions")]
    public virtual ConsentForm ConsentFormKeyNavigation { get; set; }

    [ForeignKey("ConsentQuestionKey")]
    [InverseProperty("ConsentFormQuestions")]
    public virtual ConsentQuestion ConsentQuestionKeyNavigation { get; set; }
}