// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("Deleted", Name = "nci_wi_ConsentQuestions_B158B2BE13ACA618FBDB72F7A49CD0C0")]
public partial class ConsentQuestion
{
    [Key]
    public int ConsentQuestionKey { get; set; }

    public string Title { get; set; }

    public string Question { get; set; }

    public string HelpText { get; set; }

    public int? SortOrder { get; set; }

    public bool? IsRequired { get; set; }

    public bool? IsGuardian { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Deleted { get; set; }

    public DateTime RowAdded { get; set; }

    [InverseProperty("ConsentQuestionKeyNavigation")]
    public virtual ICollection<ConsentFormQuestion> ConsentFormQuestions { get; set; } = new List<ConsentFormQuestion>();
}