// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Keyless]
[Index("ConsentQuestionKey", "LanguageKey", Name = "nci_wi_ConsentQuestionLanguages_33EBE08874ED655EF86BE4F58166152A")]
public partial class ConsentQuestionLanguage
{
    public long ConsentQuestionLanguageKey { get; set; }

    public int LanguageKey { get; set; }

    public int ConsentQuestionKey { get; set; }

    public string Title { get; set; }

    public string Question { get; set; }

    public string HelpText { get; set; }

    [ForeignKey("ConsentQuestionKey")]
    public virtual ConsentQuestion ConsentQuestionKeyNavigation { get; set; }

    [ForeignKey("LanguageKey")]
    public virtual Language LanguageKeyNavigation { get; set; }
}