// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class ConsentForm
{
    [Key]
    public int ConsentFormKey { get; set; }

    public string Heading { get; set; }

    public bool Active { get; set; }

    public DateTime RowAdded { get; set; }

    public int ClientLocationKey { get; set; }

    [InverseProperty("ConsentFormKeyNavigation")]
    public virtual ICollection<ClientLocationCustomFormAssociation> ClientLocationCustomFormAssociations { get; set; } = new List<ClientLocationCustomFormAssociation>();

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("ConsentForms")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [InverseProperty("ConsentFormKeyNavigation")]
    public virtual ICollection<ConsentFormQuestion> ConsentFormQuestions { get; set; } = new List<ConsentFormQuestion>();
}