// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("Name", Name = "UK_Countries.Name", IsUnique = true)]
public partial class Country
{
    [Key]
    public int CountryKey { get; set; }

    [Column("ISO-3166-1 ALPHA-2")]
    [StringLength(4)]
    public string Iso31661Alpha2 { get; set; }

    [Column("E.164")]
    [StringLength(12)]
    public string E164 { get; set; }

    [StringLength(100)]
    public string Name { get; set; }

    [InverseProperty("CountryKeyNavigation")]
    public virtual ICollection<State> States { get; set; } = new List<State>();
}