// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("ClientLocationKey", "WindowYear", Name = "ak_DaylightSavingTimeWindows_Year", IsUnique = true)]
[Index("ClientLocationKey", "StartDate", "EndDate", Name = "ix1DaylightSavingTimeWindows")]
public partial class DaylightSavingTimeWindow
{
    [Key]
    public int DaylightSavingTimeWindowKey { get; set; }

    public int ClientLocationKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EndDate { get; set; }

    public int? WindowYear { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("DaylightSavingTimeWindows")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }
}