// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class DeviceType
{
    [Key]
    public int DeviceTypeKey { get; set; }

    [Required]
    [StringLength(100)]
    public string DeviceDescription { get; set; }

    public bool IsTerminal { get; set; }

    public bool IsPrinter { get; set; }

    public bool IsCashDrawer { get; set; }

    public bool IsCardTerminal { get; set; }

    [InverseProperty("DeviceTypeKeyNavigation")]
    public virtual ICollection<ClientLocationDevice> ClientLocationDevices { get; set; } = new List<ClientLocationDevice>();
}