// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class DIN_ExperienceLevel
{
    [Key]
    public int ExperienceLevelKey { get; set; }

    public int ClientLocationKey { get; set; }

    [StringLength(250)]
    public string ExperienceLevelDesc { get; set; }

    public short? SortOrder { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("DIN_ExperienceLevels")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [InverseProperty("ExperienceLevelKeyNavigation")]
    public virtual ICollection<History_DIN_ExperienceLevel> History_DIN_ExperienceLevels { get; set; } = new List<History_DIN_ExperienceLevel>();
}