// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class DIN_Height
{
    [Key]
    public int HeightKey { get; set; }

    public int ClientLocationKey { get; set; }

    [StringLength(250)]
    public string HeightDesc { get; set; }

    public short? SortOrder { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("DIN_Heights")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [InverseProperty("HeightKeyNavigation")]
    public virtual ICollection<History_DIN_Height> History_DIN_Heights { get; set; } = new List<History_DIN_Height>();
}