// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class DIN_ShoeSize
{
    [Key]
    public int ShoeSizeKey { get; set; }

    public int ClientLocationKey { get; set; }

    [StringLength(250)]
    public string ShoeSizeDesc { get; set; }

    public short? SortOrder { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("DIN_ShoeSizes")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [InverseProperty("ShoeSizeKeyNavigation")]
    public virtual ICollection<History_DIN_ShoeSize> History_DIN_ShoeSizes { get; set; } = new List<History_DIN_ShoeSize>();
}