// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("DirectionTypeName", Name = "uq_DirectionTypes_DirectionTypeName", IsUnique = true)]
public partial class DirectionType
{
    [Key]
    public byte DirectionTypeKey { get; set; }

    [StringLength(50)]
    public string DirectionTypeName { get; set; }

    public DateTime? RowAdded { get; set; }
}