// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("EntityHierarchyKey", "AppointmentDate", "AppointmentTime", "ClientEmployeeKey", "OrderEntityTimeKey", Name = "uq_EntityHierarchyEmployees", IsUnique = true)]
public partial class EntityHierarchyEmployee
{
    [Key]
    public long EntityHierarchyEmployeeKey { get; set; }

    public long ClientEmployeeKey { get; set; }

    public long EntityHierarchyKey { get; set; }

    public DateOnly AppointmentDate { get; set; }

    public TimeOnly AppointmentTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    public Guid? OrderEntityTimeKey { get; set; }

    [ForeignKey("ClientEmployeeKey")]
    [InverseProperty("EntityHierarchyEmployees")]
    public virtual ClientEmployee ClientEmployeeKeyNavigation { get; set; }

    [ForeignKey("EntityHierarchyKey")]
    [InverseProperty("EntityHierarchyEmployees")]
    public virtual EntityHierarchy EntityHierarchyKeyNavigation { get; set; }
}