// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("ClientLocationResourceKey", "EntityHierarchyRateKey", Name = "uq_EntityHierarchyRateResources_CLR_EHR", IsUnique = true)]
public partial class EntityHierarchyRateResource
{
    [Key]
    public int EntityHierarchyRateResourceKey { get; set; }

    public int ClientLocationKey { get; set; }

    public long EntityHierarchyKey { get; set; }

    public long EntityHierarchyRateKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    public int ClientLocationResourceKey { get; set; }

    public short SortIndex { get; set; }

    public bool UseResource { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("EntityHierarchyRateResources")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [ForeignKey("ClientLocationResourceKey")]
    [InverseProperty("EntityHierarchyRateResources")]
    public virtual ClientLocationResource ClientLocationResourceKeyNavigation { get; set; }

    [ForeignKey("EntityHierarchyKey")]
    [InverseProperty("EntityHierarchyRateResources")]
    public virtual EntityHierarchy EntityHierarchyKeyNavigation { get; set; }

    [ForeignKey("EntityHierarchyRateKey")]
    [InverseProperty("EntityHierarchyRateResources")]
    public virtual EntityHierarchyRate EntityHierarchyRateKeyNavigation { get; set; }

    [InverseProperty("EntityHierarchyRateResourceKeyNavigation")]
    public virtual ICollection<avail_ScheduleRateResource> avail_ScheduleRateResources { get; set; } = new List<avail_ScheduleRateResource>();
}