// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class EntityHierarchyChangeWindow
{
    [Key]
    public long EntityHierarchyChangeWindowKey { get; set; }

    public byte ChangeWindowTypeKey { get; set; }

    public long EntityHierarchyKey { get; set; }

    public short FromHours { get; set; }

    public short ToHours { get; set; }

    [Column(TypeName = "money")]
    public decimal Fee { get; set; }

    [ForeignKey("EntityHierarchyKey")]
    [InverseProperty("EntityHierarchyChangeWindows")]
    public virtual EntityHierarchy EntityHierarchyKeyNavigation { get; set; }
}