// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("EntityHierarchyInventory")]
public partial class EntityHierarchyInventory
{
    [Key]
    public long EntityHierarchyInventoryKey { get; set; }

    public long EntityHierarchyKey { get; set; }

    [Required]
    public string Name { get; set; }

    [Required]
    public string Description { get; set; }

    public int Quantity { get; set; }

    public byte? MinFeet { get; set; }

    public byte? MinInches { get; set; }

    public byte? MaxFeet { get; set; }

    public byte? MaxInches { get; set; }

    public short? MinWeight { get; set; }

    public short? MaxWeight { get; set; }

    [Column(TypeName = "numeric(12, 6)")]
    public decimal? MinHeight { get; set; }

    [Column(TypeName = "numeric(12, 6)")]
    public decimal? MaxHeight { get; set; }

    public short? MaleMinAge { get; set; }

    public short? MaleMaxAge { get; set; }

    public short? FemaleMinAge { get; set; }

    public short? FemaleMaxAge { get; set; }

    public short? TurnAroundDuration { get; set; }

    public byte GenderKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Deleted { get; set; }

    [ForeignKey("EntityHierarchyKey")]
    [InverseProperty("EntityHierarchyInventories")]
    public virtual EntityHierarchy EntityHierarchyKeyNavigation { get; set; }
}