// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class EntityHierarchyTranslation
{
    [Key]
    public long EntityHierarchyTranslationKey { get; set; }

    public long EntityHierarchyKey { get; set; }

    public int LanguageKey { get; set; }

    public string ReceiptFooterHtml { get; set; }

    public string GroupEmailFooter { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    [ForeignKey("EntityHierarchyKey")]
    [InverseProperty("EntityHierarchyTranslations")]
    public virtual EntityHierarchy EntityHierarchyKeyNavigation { get; set; }

    [ForeignKey("LanguageKey")]
    [InverseProperty("EntityHierarchyTranslations")]
    public virtual Language LanguageKeyNavigation { get; set; }
}