// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class EntityHierarchyOption
{
    [Key]
    public long EntityHierarchyOptionKey { get; set; }

    public long EntityHierarchyKey { get; set; }

    [Required]
    [StringLength(200)]
    public string OptionName { get; set; }

    public bool IsPrivateTour { get; set; }

    public DateTime DateAdded { get; set; }

    public DateTime? DateDeleted { get; set; }

    [Column(TypeName = "decimal(19, 4)")]
    public decimal? Price { get; set; }

    public TimeOnly? StartTime { get; set; }

    [InverseProperty("EntityHierarchyOptionKeyNavigation")]
    public virtual ICollection<BookingAgentEntityHierarchyOption> BookingAgentEntityHierarchyOptions { get; set; } = new List<BookingAgentEntityHierarchyOption>();

    [InverseProperty("EntityHierarchyOptionKeyNavigation")]
    public virtual ICollection<ClientLocationScheduleTimeDayOption> ClientLocationScheduleTimeDayOptions { get; set; } = new List<ClientLocationScheduleTimeDayOption>();

    [ForeignKey("EntityHierarchyKey")]
    [InverseProperty("EntityHierarchyOptions")]
    public virtual EntityHierarchy EntityHierarchyKeyNavigation { get; set; }

    [InverseProperty("EntityHierarchyOptionKeyNavigation")]
    public virtual ICollection<EntityHierarchyOptionRate> EntityHierarchyOptionRates { get; set; } = new List<EntityHierarchyOptionRate>();
}