// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class EntityHierarchyOptionRate
{
    [Key]
    public long EntityHierarchyOptionRateKey { get; set; }

    public long EntityHierarchyOptionKey { get; set; }

    public long EntityHierarchyRateKey { get; set; }

    [Column(TypeName = "decimal(9, 4)")]
    public decimal? Price { get; set; }

    public DateTime RowAdded { get; set; }

    public DateTime? DateDeleted { get; set; }

    [ForeignKey("EntityHierarchyOptionKey")]
    [InverseProperty("EntityHierarchyOptionRates")]
    public virtual EntityHierarchyOption EntityHierarchyOptionKeyNavigation { get; set; }

    [ForeignKey("EntityHierarchyRateKey")]
    [InverseProperty("EntityHierarchyOptionRates")]
    public virtual EntityHierarchyRate EntityHierarchyRateKeyNavigation { get; set; }
}