// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class EntryMode
{
    [Key]
    public byte EntryModeKey { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string EntryModeDescription { get; set; }
}