// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("EventDescription", Name = "U_EventDescription", IsUnique = true)]
public partial class EventType
{
    [Key]
    public short EventTypeKey { get; set; }

    [Required]
    [StringLength(200)]
    public string EventDescription { get; set; }
}