// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("FeeKey", Name = "ix_FeeAssociations_FeeKey")]
public partial class FeeAssociation
{
    [Key]
    public long FeeAssociationKey { get; set; }

    public long? PriorFeeAssociationKey { get; set; }

    public int FeeKey { get; set; }

    public int ClientLocationKey { get; set; }

    public long? ClientLocationEntityKey { get; set; }

    public int? ProductKey { get; set; }

    public long? PhotoPackageKey { get; set; }

    public DateTime? RowAdded { get; set; }

    public DateTime? DateDeleted { get; set; }

    public bool IgnoreGlobal { get; set; }

    public bool IgnoreTaxExempt { get; set; }

    [ForeignKey("ClientLocationEntityKey")]
    [InverseProperty("FeeAssociations")]
    public virtual ClientLocationEntity ClientLocationEntityKeyNavigation { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("FeeAssociations")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [ForeignKey("FeeKey")]
    [InverseProperty("FeeAssociations")]
    public virtual Fee FeeKeyNavigation { get; set; }

    [ForeignKey("PhotoPackageKey")]
    [InverseProperty("FeeAssociations")]
    public virtual PhotoPackage PhotoPackageKeyNavigation { get; set; }

    [ForeignKey("ProductKey")]
    [InverseProperty("FeeAssociations")]
    public virtual Merchandise_Product ProductKeyNavigation { get; set; }
}