// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class GiftCard
{
    [Key]
    public long GiftCardKey { get; set; }

    public long ProductKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }
}