// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("ClientLocationEntityHierarchyDiscounts", Schema = "History")]
public partial class History_ClientLocationEntityHierarchyDiscount
{
    [Key]
    public long ClientLocationEntityHierarchyDiscountsHistoryKey { get; set; }

    public int ClientLocationEntityHierarchyDiscountKey { get; set; }

    public long? EntityHierarchyKey { get; set; }

    public long? ClientLocationDiscountKey { get; set; }

    public short? DiscountTypeKey { get; set; }

    [Column(TypeName = "numeric(30, 5)")]
    public decimal? Value { get; set; }

    public bool? ApplyOnce { get; set; }

    public DateTime DateFrom { get; set; }

    public DateTime? DateTo { get; set; }

    public bool IsCurrent { get; set; }

    [ForeignKey("ClientLocationDiscountKey")]
    [InverseProperty("History_ClientLocationEntityHierarchyDiscounts")]
    public virtual ClientLocationDiscount ClientLocationDiscountKeyNavigation { get; set; }

    [ForeignKey("ClientLocationEntityHierarchyDiscountKey")]
    [InverseProperty("History_ClientLocationEntityHierarchyDiscounts")]
    public virtual ClientLocationEntityHierarchyDiscount ClientLocationEntityHierarchyDiscountKeyNavigation { get; set; }

    [ForeignKey("DiscountTypeKey")]
    [InverseProperty("History_ClientLocationEntityHierarchyDiscounts")]
    public virtual DiscountType DiscountTypeKeyNavigation { get; set; }

    [ForeignKey("EntityHierarchyKey")]
    [InverseProperty("History_ClientLocationEntityHierarchyDiscounts")]
    public virtual EntityHierarchy EntityHierarchyKeyNavigation { get; set; }
}