// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("ClientLocationProductDiscounts", Schema = "History")]
public partial class History_ClientLocationProductDiscount
{
    [Key]
    public int ClientLocationProductDiscountHistoryKey { get; set; }

    public int ClientLocationProductDiscountKey { get; set; }

    public long? ClientLocationDiscountKey { get; set; }

    public int? ProductKey { get; set; }

    [Column(TypeName = "numeric(30, 5)")]
    public decimal? Value { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    public DateTime DateFrom { get; set; }

    public DateTime? DateTo { get; set; }

    public bool IsCurrent { get; set; }

    public bool? IsActive { get; set; }

    [ForeignKey("ClientLocationProductDiscountKey")]
    [InverseProperty("History_ClientLocationProductDiscounts")]
    public virtual ClientLocationProductDiscount ClientLocationProductDiscountKeyNavigation { get; set; }
}