// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("ClientLocationCustomFields", Schema = "History")]
public partial class History_ClientLocationCustomField
{
    [Key]
    public long ClientLocationCustomFieldHistoryKey { get; set; }

    public int ClientLocationCustomFieldKey { get; set; }

    [StringLength(250)]
    public string CustomFieldName { get; set; }

    public string CustomFieldDesc { get; set; }

    public short ResponseTypeKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateFrom { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateTo { get; set; }

    public bool IsCurrent { get; set; }

    public bool? IsRequired { get; set; }

    public bool? ShowInNotes { get; set; }

    public int ClientLocationCustomFormKey { get; set; }

    public bool? IsForMinor { get; set; }

    public bool? ShowInWaiverParticipantList { get; set; }

    public bool? ShowInConfirmationEmail { get; set; }

    [ForeignKey("ClientLocationCustomFieldKey")]
    [InverseProperty("History_ClientLocationCustomFields")]
    public virtual ClientLocationCustomField ClientLocationCustomFieldKeyNavigation { get; set; }

    [ForeignKey("ClientLocationCustomFormKey")]
    [InverseProperty("History_ClientLocationCustomFields")]
    public virtual ClientLocationCustomForm ClientLocationCustomFormKeyNavigation { get; set; }

    [ForeignKey("ResponseTypeKey")]
    [InverseProperty("History_ClientLocationCustomFields")]
    public virtual ResponseType ResponseTypeKeyNavigation { get; set; }
}