// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("EntityHierarchyRates", Schema = "History")]
[Index("EntityHierarchyRateKey", "IsCurrent", Name = "nci_wi_EntityHierarchyRates_CB226C77F1C077F6DCABAA521A30A75D")]
public partial class History_EntityHierarchyRate
{
    [Key]
    public long EntityHierarchyRatesHistoryKey { get; set; }

    public long? EntityHierarchyRateKey { get; set; }

    public long EntityHierarchyKey { get; set; }

    [StringLength(250)]
    public string Name { get; set; }

    [StringLength(250)]
    public string InternalName { get; set; }

    public string Description { get; set; }

    [Column(TypeName = "decimal(19, 4)")]
    public decimal? Price { get; set; }

    public int? MinAge { get; set; }

    public int? MaxAge { get; set; }

    public short? MaxParticipants { get; set; }

    [Column(TypeName = "decimal(19, 4)")]
    public decimal? SlashThroughPrice { get; set; }

    public bool? IsFromPrice { get; set; }

    public bool? InternalUseOnly { get; set; }

    public int? Duration { get; set; }

    public short? MinParticipants { get; set; }

    public bool? HideFromCustomer { get; set; }

    public bool? IsPrivateTourRate { get; set; }

    public short? DefaultParticipants { get; set; }

    public bool? DoesNotRequireWaiver { get; set; }

    public DateTime DateFrom { get; set; }

    public DateTime? DateTo { get; set; }

    public bool? IsActive { get; set; }

    public bool IsCurrent { get; set; }

    [Column("Resources_AskForWaiverCount")]
    public bool? ResourcesAskForWaiverCount { get; set; }

    [Column("Resources_ExcludeFromWaiverCount")]
    public bool? ResourcesExcludeFromWaiverCount { get; set; }

    [Column("Resources_SeatsPerRate")]
    public int? ResourcesSeatsPerRate { get; set; }

    public bool? EnableExpiration { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ExpirationDate { get; set; }

    [ForeignKey("EntityHierarchyKey")]
    [InverseProperty("History_EntityHierarchyRates")]
    public virtual EntityHierarchy EntityHierarchyKeyNavigation { get; set; }

    [ForeignKey("EntityHierarchyRateKey")]
    [InverseProperty("History_EntityHierarchyRates")]
    public virtual EntityHierarchyRate EntityHierarchyRateKeyNavigation { get; set; }
}