// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("ProductVariablePrices", Schema = "History")]
public partial class History_ProductVariablePrice
{
    [Key]
    public int ProductVariablePriceHistoryKey { get; set; }

    public int ProductVariablePriceKey { get; set; }

    public int ProductKey { get; set; }

    [StringLength(250)]
    public string PriceName { get; set; }

    public string PriceDesc { get; set; }

    [Column(TypeName = "money")]
    public decimal? Price { get; set; }

    public int? DurationInMinutes { get; set; }

    public int? ParentProductVariablePriceKey { get; set; }

    public DateTime DateFrom { get; set; }

    public DateTime? DateTo { get; set; }

    public bool IsCurrent { get; set; }

    public short? DurationTypeKey { get; set; }

    public TimeOnly? ReturnTime { get; set; }

    public DateOnly? ReturnDate { get; set; }

    [ForeignKey("ParentProductVariablePriceKey")]
    [InverseProperty("History_ProductVariablePriceParentProductVariablePriceKeyNavigations")]
    public virtual Merchandise_ProductVariablePrice ParentProductVariablePriceKeyNavigation { get; set; }

    [ForeignKey("ProductKey")]
    [InverseProperty("History_ProductVariablePrices")]
    public virtual Merchandise_Product ProductKeyNavigation { get; set; }

    [ForeignKey("ProductVariablePriceKey")]
    [InverseProperty("History_ProductVariablePriceProductVariablePriceKeyNavigations")]
    public virtual Merchandise_ProductVariablePrice ProductVariablePriceKeyNavigation { get; set; }
}