// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("DIN_ShoeSizes", Schema = "History")]
public partial class History_DIN_ShoeSize
{
    [Key]
    public int ShoeSizeHistoryKey { get; set; }

    public int ShoeSizeKey { get; set; }

    public int ClientLocationKey { get; set; }

    [StringLength(250)]
    public string ShoeSizeDesc { get; set; }

    public DateTime DateFrom { get; set; }

    public DateTime? DateTo { get; set; }

    public bool IsCurrent { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("History_DIN_ShoeSizes")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [ForeignKey("ShoeSizeKey")]
    [InverseProperty("History_DIN_ShoeSizes")]
    public virtual DIN_ShoeSize ShoeSizeKeyNavigation { get; set; }
}