// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("ClientLocationCustomFieldResponses", Schema = "History")]
public partial class History_ClientLocationCustomFieldResponse
{
    [Key]
    public long ClientLocationCustomFieldResponseHistoryKey { get; set; }

    public int ClientLocationCustomFieldResponseKey { get; set; }

    public int ClientLocationCustomFieldKey { get; set; }

    [Required]
    public string ResponseLabel { get; set; }

    [Column("Response_Boolean")]
    public bool? ResponseBoolean { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateFrom { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateTo { get; set; }

    public bool IsCurrent { get; set; }

    [ForeignKey("ClientLocationCustomFieldKey")]
    [InverseProperty("History_ClientLocationCustomFieldResponses")]
    public virtual ClientLocationCustomField ClientLocationCustomFieldKeyNavigation { get; set; }

    [ForeignKey("ClientLocationCustomFieldResponseKey")]
    [InverseProperty("History_ClientLocationCustomFieldResponses")]
    public virtual ClientLocationCustomFieldResponse ClientLocationCustomFieldResponseKeyNavigation { get; set; }
}