// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("BookingAgentInvoices", Schema = "History")]
public partial class History_BookingAgentInvoice
{
    [Key]
    public long BookingAgentInvoiceHistoryKey { get; set; }

    public long BookingAgentInvoiceKey { get; set; }

    public long? BookingAgentKey { get; set; }

    public long? BookingAgentBillingKey { get; set; }

    [StringLength(250)]
    public string Number { get; set; }

    [Column(TypeName = "decimal(19, 5)")]
    public decimal? AmountDue { get; set; }

    public DateTime? BeginDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime? DueDate { get; set; }

    public string SentTo { get; set; }

    public DateOnly? DatePaid { get; set; }

    public string PdfUrl { get; set; }

    public string CsvUrl { get; set; }

    [Column(TypeName = "decimal(19, 5)")]
    public decimal? AmountPaid { get; set; }

    public DateTime DateFrom { get; set; }

    public DateTime? DateTo { get; set; }

    public bool IsCurrent { get; set; }
}