// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("DIN_Weights", Schema = "History")]
public partial class History_DIN_Weight
{
    [Key]
    public int WeightHistoryKey { get; set; }

    public int WeightKey { get; set; }

    public int ClientLocationKey { get; set; }

    [StringLength(250)]
    public string WeightDesc { get; set; }

    public DateTime DateFrom { get; set; }

    public DateTime? DateTo { get; set; }

    public bool IsCurrent { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("History_DIN_Weights")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [ForeignKey("WeightKey")]
    [InverseProperty("History_DIN_Weights")]
    public virtual DIN_Weight WeightKeyNavigation { get; set; }
}