// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("BookingAgentEntityHierarchyRates", Schema = "History")]
[Index("BookingAgentEntityHierarchyRateKey", Name = "ix_History_BookingAgentEntityHierarchyRates_BookingagentEntityHierarchyRateKey")]
public partial class History_BookingAgentEntityHierarchyRate
{
    [Key]
    public long BookingAgentEntityHierarchyRateHistoryKey { get; set; }

    public long BookingAgentEntityHierarchyRateKey { get; set; }

    [Column(TypeName = "numeric(25, 7)")]
    public decimal? Commission { get; set; }

    public bool? Sellable { get; set; }

    [Column(TypeName = "money")]
    public decimal? Price { get; set; }

    [Column(TypeName = "money")]
    public decimal? MaxPackageDiscount { get; set; }

    [Column(TypeName = "numeric(25, 7)")]
    public decimal? TransportationCommission { get; set; }

    public DateTime DateFrom { get; set; }

    public DateTime? DateTo { get; set; }

    public bool IsCurrent { get; set; }

    public bool? IsCommissionOnTaxedAmount { get; set; }

    public bool? CollectsTransportCost { get; set; }

    [ForeignKey("BookingAgentEntityHierarchyRateKey")]
    [InverseProperty("History_BookingAgentEntityHierarchyRates")]
    public virtual BookingAgentEntityHierarchyRate BookingAgentEntityHierarchyRateKeyNavigation { get; set; }
}