// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("DIN_Heights", Schema = "History")]
public partial class History_DIN_Height
{
    [Key]
    public int HeightHistoryKey { get; set; }

    public int HeightKey { get; set; }

    public int ClientLocationKey { get; set; }

    [StringLength(250)]
    public string HeightDesc { get; set; }

    public DateTime DateFrom { get; set; }

    public DateTime? DateTo { get; set; }

    public bool IsCurrent { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("History_DIN_Heights")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [ForeignKey("HeightKey")]
    [InverseProperty("History_DIN_Heights")]
    public virtual DIN_Height HeightKeyNavigation { get; set; }
}