// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class Language
{
    [Key]
    public int LanguageKey { get; set; }

    [Required]
    [StringLength(200)]
    public string Description { get; set; }

    [Required]
    [StringLength(200)]
    public string FriendlyName { get; set; }

    [InverseProperty("LanguageKeyNavigation")]
    public virtual ICollection<ClientLocationLanguage> ClientLocationLanguages { get; set; } = new List<ClientLocationLanguage>();

    [InverseProperty("LanguageKeyNavigation")]
    public virtual ICollection<ClientLocationTranslation> ClientLocationTranslations { get; set; } = new List<ClientLocationTranslation>();

    [InverseProperty("LanguageKeyNavigation")]
    public virtual ICollection<EntityHierarchyTranslation> EntityHierarchyTranslations { get; set; } = new List<EntityHierarchyTranslation>();
}