// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("ProductCategories", Schema = "Merchandise")]
public partial class Merchandise_ProductCategory
{
    [Key]
    public short ProductCategoryKey { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Description { get; set; }

    public int? ClientKey { get; set; }

    public int? ClientLocationKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    public short SortOrder { get; set; }

    [ForeignKey("ClientKey")]
    [InverseProperty("Merchandise_ProductCategories")]
    public virtual Client ClientKeyNavigation { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("Merchandise_ProductCategories")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [InverseProperty("ProductCategoryKeyNavigation")]
    public virtual ICollection<Merchandise_ProductCategoryAssociation> Merchandise_ProductCategoryAssociations { get; set; } = new List<Merchandise_ProductCategoryAssociation>();

    [InverseProperty("ProductCategoryKeyNavigation")]
    public virtual ICollection<Merchandise_Product> Merchandise_Products { get; set; } = new List<Merchandise_Product>();
}