// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("ProductSizes", Schema = "Merchandise")]
public partial class Merchandise_ProductSize
{
    [Key]
    public short ProductSizeKey { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Description { get; set; }

    public short SortOrder { get; set; }

    public int? ClientLocationKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("Merchandise_ProductSizes")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [InverseProperty("ProductSizeKeyNavigation")]
    public virtual ICollection<Merchandise_Product> Merchandise_Products { get; set; } = new List<Merchandise_Product>();
}