// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("ProductVariablePrices", Schema = "Merchandise")]
public partial class Merchandise_ProductVariablePrice
{
    [Key]
    public int ProductVariablePriceKey { get; set; }

    public int ProductKey { get; set; }

    [Required]
    [StringLength(250)]
    public string PriceName { get; set; }

    public string PriceDesc { get; set; }

    [Column(TypeName = "money")]
    public decimal Price { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    public int? DurationInMinutes { get; set; }

    public int? ParentProductVariablePriceKey { get; set; }

    public short DurationTypeKey { get; set; }

    public TimeOnly? ReturnTime { get; set; }

    public DateOnly? ReturnDate { get; set; }

    [InverseProperty("ParentProductVariablePriceKeyNavigation")]
    public virtual ICollection<History_ProductVariablePrice> History_ProductVariablePriceParentProductVariablePriceKeyNavigations { get; set; } = new List<History_ProductVariablePrice>();

    [InverseProperty("ProductVariablePriceKeyNavigation")]
    public virtual ICollection<History_ProductVariablePrice> History_ProductVariablePriceProductVariablePriceKeyNavigations { get; set; } = new List<History_ProductVariablePrice>();

    [InverseProperty("ParentProductVariablePriceKeyNavigation")]
    public virtual ICollection<Merchandise_ProductVariablePrice> InverseParentProductVariablePriceKeyNavigation { get; set; } = new List<Merchandise_ProductVariablePrice>();

    [ForeignKey("ParentProductVariablePriceKey")]
    [InverseProperty("InverseParentProductVariablePriceKeyNavigation")]
    public virtual Merchandise_ProductVariablePrice ParentProductVariablePriceKeyNavigation { get; set; }

    [ForeignKey("ProductKey")]
    [InverseProperty("Merchandise_ProductVariablePrices")]
    public virtual Merchandise_Product ProductKeyNavigation { get; set; }
}