// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("ProductAddOnEntityHierarchies", Schema = "Merchandise")]
[Index("EntityHierarchyKey", Name = "ix_Merchandise_ProductAddOnEntityHierarchies_EntityHierarchyKey")]
[Index("ProductKey", Name = "ix_Merchandise_ProductAddOnEntityHierarchies_ProductKey")]
public partial class Merchandise_ProductAddOnEntityHierarchy
{
    [Key]
    public long ProductAddOnEntityHierarchyKey { get; set; }

    public int ProductKey { get; set; }

    public long EntityHierarchyKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    [ForeignKey("EntityHierarchyKey")]
    [InverseProperty("Merchandise_ProductAddOnEntityHierarchies")]
    public virtual EntityHierarchy EntityHierarchyKeyNavigation { get; set; }

    [ForeignKey("ProductKey")]
    [InverseProperty("Merchandise_ProductAddOnEntityHierarchies")]
    public virtual Merchandise_Product ProductKeyNavigation { get; set; }
}