// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("ProductColors", Schema = "Merchandise")]
public partial class Merchandise_ProductColor
{
    [Key]
    public long ProductColorKey { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("CSSColorCode")]
    [StringLength(12)]
    [Unicode(false)]
    public string CsscolorCode { get; set; }

    public int ClientLocationKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    public short SortOrder { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("Merchandise_ProductColors")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [InverseProperty("ProductColorKeyNavigation")]
    public virtual ICollection<Merchandise_Product> Merchandise_Products { get; set; } = new List<Merchandise_Product>();
}