// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[PrimaryKey("ProductKey", "DateTaken")]
[Table("Inventories", Schema = "Merchandise")]
[Index("ProductKey", Name = "IX1_Merchandise_Inventories", IsUnique = true)]
public partial class Merchandise_Inventory
{
    [Key]
    public int ProductKey { get; set; }

    [Key]
    [Column(TypeName = "datetime")]
    public DateTime DateTaken { get; set; }

    public int QuantityOnHand { get; set; }

    public long? ClientLoginKey { get; set; }

    [ForeignKey("ClientLoginKey")]
    [InverseProperty("Merchandise_Inventories")]
    public virtual ClientLogin ClientLoginKeyNavigation { get; set; }

    [ForeignKey("ProductKey")]
    [InverseProperty("Merchandise_Inventory")]
    public virtual Merchandise_Product ProductKeyNavigation { get; set; }
}