// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("RentalNoteTypes", Schema = "Merchandise")]
public partial class Merchandise_RentalNoteType
{
    [Key]
    public int RentalNoteTypeKey { get; set; }

    [StringLength(250)]
    public string RentalNoteDesc { get; set; }

    [InverseProperty("RentalNoteTypeKeyNavigation")]
    public virtual ICollection<Merchandise_ProductRentalItemNote> Merchandise_ProductRentalItemNotes { get; set; } = new List<Merchandise_ProductRentalItemNote>();
}