// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("InventoryChangeLog", Schema = "Merchandise")]
public partial class Merchandise_InventoryChangeLog
{
    [Key]
    public long InventoryChangeLogKey { get; set; }

    public int ProductKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateChanged { get; set; }

    public int? QuantityBeforeChange { get; set; }

    public int? QuantityAfterChange { get; set; }

    public int? ChangeInQuantity { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string ChangeProcess { get; set; }

    [ForeignKey("ProductKey")]
    [InverseProperty("Merchandise_InventoryChangeLogs")]
    public virtual Merchandise_Product ProductKeyNavigation { get; set; }
}