// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("ProductCategoryAssociations", Schema = "Merchandise")]
[Index("ProductKey", Name = "ix_Merchandise_ProductCategoryAssociations_ProductKey")]
public partial class Merchandise_ProductCategoryAssociation
{
    [Key]
    public int ProductCategoryAssociationKey { get; set; }

    public int ClientLocationKey { get; set; }

    public int ProductKey { get; set; }

    public short ProductCategoryKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("Merchandise_ProductCategoryAssociations")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [ForeignKey("ProductCategoryKey")]
    [InverseProperty("Merchandise_ProductCategoryAssociations")]
    public virtual Merchandise_ProductCategory ProductCategoryKeyNavigation { get; set; }

    [ForeignKey("ProductKey")]
    [InverseProperty("Merchandise_ProductCategoryAssociations")]
    public virtual Merchandise_Product ProductKeyNavigation { get; set; }
}