// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("ProductRentalItemNotes", Schema = "Merchandise")]
public partial class Merchandise_ProductRentalItemNote
{
    [Key]
    public int ProductRentalItemNoteKey { get; set; }

    public int ProductRentalItemKey { get; set; }

    public long? ConsentKey { get; set; }

    public long? ConsentMinorKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    [Required]
    public string Note { get; set; }

    public long ClientLoginKey { get; set; }

    public int RentalNoteTypeKey { get; set; }

    [ForeignKey("ClientLoginKey")]
    [InverseProperty("Merchandise_ProductRentalItemNotes")]
    public virtual ClientLogin ClientLoginKeyNavigation { get; set; }

    [ForeignKey("ProductRentalItemKey")]
    [InverseProperty("Merchandise_ProductRentalItemNotes")]
    public virtual Merchandise_ProductRentalItem ProductRentalItemKeyNavigation { get; set; }

    [ForeignKey("RentalNoteTypeKey")]
    [InverseProperty("Merchandise_ProductRentalItemNotes")]
    public virtual Merchandise_RentalNoteType RentalNoteTypeKeyNavigation { get; set; }
}