// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("MessageTemplateTypeName", Name = "uq_MessageTemplateTypes_MessageTemplateTypeName", IsUnique = true)]
public partial class MessageTemplateType
{
    [Key]
    public byte MessageTemplateTypeKey { get; set; }

    [StringLength(50)]
    public string MessageTemplateTypeName { get; set; }

    [InverseProperty("MessageTemplateTypeKeyNavigation")]
    public virtual ICollection<MessageTemplate> MessageTemplates { get; set; } = new List<MessageTemplate>();
}