// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("NotificationTypes", Schema = "NotificationSystem")]
public partial class NotificationSystem_NotificationType
{
    [Key]
    public short NotificationTypeKey { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string Description { get; set; }

    [InverseProperty("NotificationTypeKeyNavigation")]
    public virtual ICollection<EmailTemplate> EmailTemplates { get; set; } = new List<EmailTemplate>();
}