// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class OnlineTravelAgency
{
    [Key]
    public long OnlineTravelAgencyKey { get; set; }

    [Required]
    [StringLength(250)]
    public string OnlineTravelAgencyName { get; set; }

    public long ExpiresMinutes { get; set; }

    [Column("OnlineTravelAgencyGUID")]
    public Guid OnlineTravelAgencyGuid { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string OtaUser { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string OtaSecret { get; set; }

    public bool Enabled { get; set; }

    [InverseProperty("OnlineTravelAgencyKeyNavigation")]
    public virtual ICollection<BookingAgentEntityHierarchy> BookingAgentEntityHierarchies { get; set; } = new List<BookingAgentEntityHierarchy>();

    [InverseProperty("OnlineTravelAgencyKeyNavigation")]
    public virtual ICollection<BookingAgent> BookingAgents { get; set; } = new List<BookingAgent>();

    [InverseProperty("OnlineTravelAgencyKeyNavigation")]
    public virtual ICollection<Fee> Fees { get; set; } = new List<Fee>();
}