// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("OrderStatus")]
public partial class OrderStatus
{
    [Key]
    public int OrderStatusKey { get; set; }

    [Required]
    public string Description { get; set; }
}