// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class PackageGroup
{
    [Key]
    public Guid PackageGroupKey { get; set; }

    public Guid PackageKey { get; set; }

    [Required]
    [StringLength(250)]
    public string GroupName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    public short? ReservedSpaces { get; set; }

    [InverseProperty("PackageGroupKeyNavigation")]
    public virtual ICollection<PackageDetailGroup> PackageDetailGroups { get; set; } = new List<PackageDetailGroup>();

    [ForeignKey("PackageKey")]
    [InverseProperty("PackageGroups")]
    public virtual Package PackageKeyNavigation { get; set; }
}