// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class PackageDetailRate
{
    [Key]
    public int PackageDetailRateKey { get; set; }

    public Guid PackageDetailKey { get; set; }

    public long EntityHierarchyRateKey { get; set; }

    [Column(TypeName = "money")]
    public decimal RateDiscount { get; set; }

    public DateTime? RowAdded { get; set; }

    public DateTime? DateDeleted { get; set; }

    public bool Include { get; set; }

    [ForeignKey("EntityHierarchyRateKey")]
    [InverseProperty("PackageDetailRates")]
    public virtual EntityHierarchyRate EntityHierarchyRateKeyNavigation { get; set; }

    [ForeignKey("PackageDetailKey")]
    [InverseProperty("PackageDetailRates")]
    public virtual PackageDetail PackageDetailKeyNavigation { get; set; }
}