// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class PackageType
{
    [Key]
    public byte PackageTypeKey { get; set; }

    [Required]
    [StringLength(250)]
    public string PackageTypeName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    [InverseProperty("PackageTypeKeyNavigation")]
    public virtual ICollection<Package> Packages { get; set; } = new List<Package>();
}