// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class PaymentGateway
{
    [Key]
    public int PaymentGatewayKey { get; set; }

    [Required]
    public string Name { get; set; }

    [InverseProperty("PaymentGatewayKeyNavigation")]
    public virtual ICollection<ClientPaymentGateway> ClientPaymentGateways { get; set; } = new List<ClientPaymentGateway>();
}