// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class PhotoPackage
{
    [Key]
    public long PhotoPackageKey { get; set; }

    public long ClientLocationEntityKey { get; set; }

    public short MinQuantity { get; set; }

    public short? MaxQuantity { get; set; }

    [Column(TypeName = "money")]
    public decimal Price { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public short? PhotoPackageTypeKey { get; set; }

    public byte Sequence { get; set; }

    public bool IsActive { get; set; }

    public int? ParticipantsBooked { get; set; }

    [Column(TypeName = "money")]
    public decimal? AddOnDiscount { get; set; }

    [ForeignKey("ClientLocationEntityKey")]
    [InverseProperty("PhotoPackages")]
    public virtual ClientLocationEntity ClientLocationEntityKeyNavigation { get; set; }

    [InverseProperty("PhotoPackageKeyNavigation")]
    public virtual ICollection<FeeAssociation> FeeAssociations { get; set; } = new List<FeeAssociation>();

    [InverseProperty("PhotoPackageKeyNavigation")]
    public virtual ICollection<PackageDetail> PackageDetails { get; set; } = new List<PackageDetail>();

    [ForeignKey("PhotoPackageTypeKey")]
    [InverseProperty("PhotoPackages")]
    public virtual PhotoPackageType PhotoPackageTypeKeyNavigation { get; set; }
}