// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class PickupRouteSchedule
{
    [Key]
    public long PickupRouteScheduleKey { get; set; }

    public int PickupRouteKey { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string ScheduleName { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    public short MaxPickupLocations { get; set; }

    [ForeignKey("PickupRouteKey")]
    [InverseProperty("PickupRouteSchedules")]
    public virtual PickupRoute PickupRouteKeyNavigation { get; set; }

    [InverseProperty("PickupRouteScheduleKeyNavigation")]
    public virtual ICollection<PickupRouteScheduleTime> PickupRouteScheduleTimes { get; set; } = new List<PickupRouteScheduleTime>();
}