// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class PickupLocation
{
    [Key]
    public long PickupLocationKey { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string LocationName { get; set; }

    [Column(TypeName = "numeric(18, 14)")]
    public decimal? Latitude { get; set; }

    [Column(TypeName = "numeric(18, 14)")]
    public decimal? Longitude { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Address { get; set; }

    public int ClientLocationKey { get; set; }

    public int? MaxRiders { get; set; }

    public TimeOnly? TransportationTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    public bool IsActive { get; set; }

    public string Instructions { get; set; }

    public string ReturnInstructions { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("PickupLocations")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [InverseProperty("PickupLocationKeyNavigation")]
    public virtual ICollection<PickupRouteStopDay> PickupRouteStopDays { get; set; } = new List<PickupRouteStopDay>();

    [InverseProperty("PickupLocationKeyNavigation")]
    public virtual ICollection<PickupRouteStop> PickupRouteStops { get; set; } = new List<PickupRouteStop>();
}