// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("PickupRouteKey", "PickupVehicleKey", "PickupDate", Name = "uq_PickupRouteEmployees_Route_Vehicle_Date", IsUnique = true)]
public partial class PickupRouteEmployee
{
    [Key]
    public int PickupRouteEmployeeKey { get; set; }

    public int PickupRouteKey { get; set; }

    public int PickupVehicleKey { get; set; }

    public DateOnly PickupDate { get; set; }

    public int ClientLocationKey { get; set; }

    public long? ClientLoginKey { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("PickupRouteEmployees")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [ForeignKey("ClientLoginKey")]
    [InverseProperty("PickupRouteEmployees")]
    public virtual ClientLogin ClientLoginKeyNavigation { get; set; }

    [ForeignKey("PickupRouteKey")]
    [InverseProperty("PickupRouteEmployees")]
    public virtual PickupRoute PickupRouteKeyNavigation { get; set; }

    [ForeignKey("PickupVehicleKey")]
    [InverseProperty("PickupRouteEmployees")]
    public virtual PickupVehicle PickupVehicleKeyNavigation { get; set; }
}