// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("PickupStatus")]
public partial class PickupStatus
{
    [Key]
    public byte PickupStatusKey { get; set; }

    [Required]
    [StringLength(250)]
    public string Description { get; set; }
}