// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class PickupRouteVehicle
{
    [Key]
    public int PickupRouteVehicleKey { get; set; }

    public int PickupRouteKey { get; set; }

    public int PickupVehicleKey { get; set; }

    public bool IsDefault { get; set; }

    public bool IsAvailable { get; set; }

    public bool IsAssigned { get; set; }

    public DateOnly? PickupDate { get; set; }

    public bool ApplyToOrder { get; set; }

    [ForeignKey("PickupRouteKey")]
    [InverseProperty("PickupRouteVehicles")]
    public virtual PickupRoute PickupRouteKeyNavigation { get; set; }

    [ForeignKey("PickupVehicleKey")]
    [InverseProperty("PickupRouteVehicles")]
    public virtual PickupVehicle PickupVehicleKeyNavigation { get; set; }
}