// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class PickupRouteDay
{
    [Key]
    public int PickupRouteDayKey { get; set; }

    public int PickupRouteKey { get; set; }

    public DateOnly PickupDate { get; set; }

    public short MaxRiders { get; set; }

    [ForeignKey("PickupRouteKey")]
    [InverseProperty("PickupRouteDays")]
    public virtual PickupRoute PickupRouteKeyNavigation { get; set; }
}