// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class PickupRouteScheduleTimeDay
{
    [Key]
    public long PickupRouteScheduleTimeDayKey { get; set; }

    public long PickupRouteScheduleTimeKey { get; set; }

    public byte DaysOfTheWeekKey { get; set; }

    [ForeignKey("DaysOfTheWeekKey")]
    [InverseProperty("PickupRouteScheduleTimeDays")]
    public virtual DaysOfTheWeek DaysOfTheWeekKeyNavigation { get; set; }

    [ForeignKey("PickupRouteScheduleTimeKey")]
    [InverseProperty("PickupRouteScheduleTimeDays")]
    public virtual PickupRouteScheduleTime PickupRouteScheduleTimeKeyNavigation { get; set; }
}