// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class PickupRouteScheduleTime
{
    [Key]
    public long PickupRouteScheduleTimeKey { get; set; }

    public long PickupRouteScheduleKey { get; set; }

    public TimeOnly Time { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    public TimeOnly? TourTime { get; set; }

    [ForeignKey("PickupRouteScheduleKey")]
    [InverseProperty("PickupRouteScheduleTimes")]
    public virtual PickupRouteSchedule PickupRouteScheduleKeyNavigation { get; set; }

    [InverseProperty("PickupRouteScheduleTimeKeyNavigation")]
    public virtual ICollection<PickupRouteScheduleTimeDay> PickupRouteScheduleTimeDays { get; set; } = new List<PickupRouteScheduleTimeDay>();
}