// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class PickupVehicle
{
    [Key]
    public int PickupVehicleKey { get; set; }

    public int ClientLocationKey { get; set; }

    public short MaxRiders { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column(TypeName = "money")]
    public decimal? PickupCost { get; set; }

    public int? TransportationVendorKey { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("PickupVehicles")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [InverseProperty("PickupVehicleKeyNavigation")]
    public virtual ICollection<PickupRouteEmployee> PickupRouteEmployees { get; set; } = new List<PickupRouteEmployee>();

    [InverseProperty("PickupVehicleKeyNavigation")]
    public virtual ICollection<PickupRouteVehicle> PickupRouteVehicles { get; set; } = new List<PickupRouteVehicle>();
}