// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class PickupRouteStop
{
    [Key]
    public long PickupRouteStopKey { get; set; }

    public int PickupRouteKey { get; set; }

    public byte StopSequence { get; set; }

    public long PickupLocationKey { get; set; }

    public TimeOnly DepartureTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    public bool SchedulingCutoff { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }

    /// <summary>
    /// If this column is populated, marked as deleted or otherwise, then all route stops for the day must be explicitly populated
    /// </summary>
    public DateOnly? PickupDate { get; set; }

    [ForeignKey("PickupLocationKey")]
    [InverseProperty("PickupRouteStops")]
    public virtual PickupLocation PickupLocationKeyNavigation { get; set; }

    [ForeignKey("PickupRouteKey")]
    [InverseProperty("PickupRouteStops")]
    public virtual PickupRoute PickupRouteKeyNavigation { get; set; }
}