// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class PickupRoute
{
    [Key]
    public int PickupRouteKey { get; set; }

    public int? PickupVehicleKey { get; set; }

    public TimeOnly RouteStartTime { get; set; }

    public TimeOnly Duration { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Name { get; set; }

    public int ClientLocationKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    public bool DisplayPickupRouteStartTime { get; set; }

    public int? TransportationVendorNotificationKey { get; set; }

    public short? MaximumOnSiteWait { get; set; }

    public byte DirectionTypeKey { get; set; }

    public bool IsActive { get; set; }

    public short MaxRiders { get; set; }

    [InverseProperty("PickupRouteKeyNavigation")]
    public virtual ICollection<ClientLocationEntityPickupRoute> ClientLocationEntityPickupRoutes { get; set; } = new List<ClientLocationEntityPickupRoute>();

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("PickupRoutes")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [InverseProperty("PickupRouteKeyNavigation")]
    public virtual ICollection<ClientLocationScheduleTimeDay> ClientLocationScheduleTimeDays { get; set; } = new List<ClientLocationScheduleTimeDay>();

    [InverseProperty("PickupRouteKeyNavigation")]
    public virtual ICollection<PickupRouteDay> PickupRouteDays { get; set; } = new List<PickupRouteDay>();

    [InverseProperty("PickupRouteKeyNavigation")]
    public virtual ICollection<PickupRouteEmployee> PickupRouteEmployees { get; set; } = new List<PickupRouteEmployee>();

    [InverseProperty("PickupRouteKeyNavigation")]
    public virtual ICollection<PickupRouteSchedule> PickupRouteSchedules { get; set; } = new List<PickupRouteSchedule>();

    [InverseProperty("PickupRouteKeyNavigation")]
    public virtual ICollection<PickupRouteStopDay> PickupRouteStopDays { get; set; } = new List<PickupRouteStopDay>();

    [InverseProperty("PickupRouteKeyNavigation")]
    public virtual ICollection<PickupRouteStop> PickupRouteStops { get; set; } = new List<PickupRouteStop>();

    [InverseProperty("PickupRouteKeyNavigation")]
    public virtual ICollection<PickupRouteVehicle> PickupRouteVehicles { get; set; } = new List<PickupRouteVehicle>();

    [InverseProperty("PickupRouteKeyNavigation")]
    public virtual ICollection<avail_ScheduleTime> avail_ScheduleTimes { get; set; } = new List<avail_ScheduleTime>();
}