// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class Register
{
    [Key]
    public Guid RegisterKey { get; set; }

    public int ClientLocationKey { get; set; }

    [Column("UUID")]
    public Guid Uuid { get; set; }

    [Required]
    [StringLength(250)]
    public string Alias { get; set; }

    public bool EnableCashManagement { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime BeginDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndDate { get; set; }

    [Column(TypeName = "money")]
    public decimal DefaultStartingCash { get; set; }

    public bool AutoEmailReport { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string AutoEmailReportRecipient { get; set; }

    [InverseProperty("RegisterKeyNavigation")]
    public virtual ICollection<CashDrawer_Session> CashDrawer_Sessions { get; set; } = new List<CashDrawer_Session>();

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("Registers")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }
}