// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("ProcessedOrders", Schema = "remediate")]
public partial class remediate_ProcessedOrder
{
    [Key]
    public long ProcessedOrderKey { get; set; }

    public Guid OrderKey { get; set; }

    [StringLength(250)]
    public string OrderNumber { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateProcessed { get; set; }

    public long MessageQueueKey { get; set; }

    public short MessageCount { get; set; }

    public int ClientLocationKey { get; set; }

    public DateTime MinRowAdded { get; set; }

    public DateTime MaxRowAdded { get; set; }

    [Required]
    [Unicode(false)]
    public string ErrorMessage { get; set; }

    [StringLength(512)]
    [Unicode(false)]
    public string ProcedureName { get; set; }

    public bool RequiresFollowup { get; set; }

    public byte ResultTypeKey { get; set; }

    [StringLength(500)]
    public string PreProcessFileName { get; set; }

    [StringLength(500)]
    public string PostProcessFileName { get; set; }

    [ForeignKey("ClientLocationKey")]
    [InverseProperty("remediate_ProcessedOrders")]
    public virtual ClientLocation ClientLocationKeyNavigation { get; set; }

    [ForeignKey("ResultTypeKey")]
    [InverseProperty("remediate_ProcessedOrders")]
    public virtual remediate_ProcessOrderResultType ResultTypeKeyNavigation { get; set; }
}