// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("ProcessOrderResultTypes", Schema = "remediate")]
[Index("ResultName", Name = "uq_remediate_ProcessOrderResultTypes_ResultName", IsUnique = true)]
public partial class remediate_ProcessOrderResultType
{
    [Key]
    public byte ResultTypeKey { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string ResultName { get; set; }

    [InverseProperty("ResultTypeKeyNavigation")]
    public virtual ICollection<remediate_ProcessedOrder> remediate_ProcessedOrders { get; set; } = new List<remediate_ProcessedOrder>();
}