// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("ResponseType1", Name = "uq_ResponseTypes_ResponseType", IsUnique = true)]
public partial class ResponseType
{
    [Key]
    public short ResponseTypeKey { get; set; }

    [Required]
    [Column("ResponseType")]
    [StringLength(250)]
    public string ResponseType1 { get; set; }

    public short SortOrder { get; set; }

    public DateTime RowAdded { get; set; }

    public DateTime? DateDeleted { get; set; }

    [InverseProperty("ResponseTypeKeyNavigation")]
    public virtual ICollection<ClientLocationCustomField> ClientLocationCustomFields { get; set; } = new List<ClientLocationCustomField>();

    [InverseProperty("ResponseTypeKeyNavigation")]
    public virtual ICollection<History_ClientLocationCustomField> History_ClientLocationCustomFields { get; set; } = new List<History_ClientLocationCustomField>();
}