// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class Service
{
    [Key]
    public int ServiceKey { get; set; }

    [Required]
    [StringLength(500)]
    public string ServiceName { get; set; }

    [InverseProperty("ServiceKeyNavigation")]
    public virtual ICollection<ServiceLog> ServiceLogs { get; set; } = new List<ServiceLog>();
}