// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("ServiceKey", "ServiceLogKey", Name = "ix1ServiceLogs")]
public partial class ServiceLog
{
    [Key]
    public long ServiceLogKey { get; set; }

    public int ServiceKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EndTime { get; set; }

    public string Data { get; set; }

    [ForeignKey("ServiceKey")]
    [InverseProperty("ServiceLogs")]
    public virtual Service ServiceKeyNavigation { get; set; }
}