// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class Session
{
    [Key]
    [StringLength(88)]
    public string SessionId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Expires { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LockDate { get; set; }

    public int LockCookie { get; set; }

    public bool Locked { get; set; }

    public byte[] SessionItem { get; set; }

    public int Flags { get; set; }

    public int Timeout { get; set; }
}