// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("CurrencyCodes", Schema = "Square")]
public partial class Square_CurrencyCode
{
    [Key]
    public byte CurrencyKey { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string CurrencyCode { get; set; }
}