// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("SquareSDKTypes", Schema = "Square")]
public partial class Square_SquareSDKType
{
    [Key]
    [Column("SquareSDKTypeKey")]
    public byte SquareSdktypeKey { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Description { get; set; }
}