// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class State
{
    [Key]
    public int StateKey { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Abbreviation { get; set; }

    public int CountryKey { get; set; }

    [ForeignKey("CountryKey")]
    [InverseProperty("States")]
    public virtual Country CountryKeyNavigation { get; set; }
}