// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Keyless]
[Table("OrderStatusEnum", Schema = "System")]
public partial class System_OrderStatusEnum
{
    public int? OrderStatusEnum { get; set; }

    public short? OrderStatusKey { get; set; }
}