// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("ZCTA", Schema = "System")]
public partial class System_ZCTum
{
    [Key]
    [Column("ZIPCode")]
    [StringLength(9)]
    [Unicode(false)]
    public string Zipcode { get; set; }

    [Column("POP10")]
    public int Pop10 { get; set; }

    [Column("HU10")]
    public int Hu10 { get; set; }

    [Column("ALAND")]
    public long Aland { get; set; }

    [Column("AWATER")]
    public long Awater { get; set; }

    [Column("ALAND_SQMI", TypeName = "numeric(12, 3)")]
    public decimal AlandSqmi { get; set; }

    [Column("AWATER_SQMI", TypeName = "numeric(12, 3)")]
    public decimal AwaterSqmi { get; set; }

    [Column("INTPLAT", TypeName = "numeric(20, 5)")]
    public decimal Intplat { get; set; }

    [Column("INTPLONG", TypeName = "numeric(20, 5)")]
    public decimal Intplong { get; set; }
}