// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("spt_values", Schema = "System")]
public partial class System_spt_value
{
    [Key]
    [Column("spt_values_pk")]
    public int SptValuesPk { get; set; }

    [Column("name")]
    [StringLength(35)]
    public string Name { get; set; }

    [Column("number")]
    public int Number { get; set; }

    [Required]
    [Column("type")]
    [StringLength(3)]
    public string Type { get; set; }

    [Column("low")]
    public int? Low { get; set; }

    [Column("high")]
    public int? High { get; set; }

    [Column("status")]
    public int? Status { get; set; }
}