// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

public partial class SystemEntityType
{
    [Key]
    public short SystemEntityTypeKey { get; set; }

    [Column("SystemEntityHierarchyID")]
    public HierarchyId SystemEntityHierarchyId { get; set; }

    [StringLength(250)]
    public string Name { get; set; }

    public bool? IsMultiOrder { get; set; }

    [StringLength(50)]
    public string IconClass { get; set; }

    [StringLength(7)]
    public string HexColor { get; set; }
}