// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("EmailTypes", Schema = "System")]
public partial class System_EmailType
{
    [Key]
    public short EmailTypeKey { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Name { get; set; }

    [InverseProperty("EmailTypeKeyNavigation")]
    public virtual ICollection<ClientLocationEmailTemplate> ClientLocationEmailTemplates { get; set; } = new List<ClientLocationEmailTemplate>();
}