// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("ApplicationRolesApplicationObjects", Schema = "System")]
public partial class System_ApplicationRolesApplicationObject
{
    public short ApplicationRoleKey { get; set; }

    public int ApplicationObjectKey { get; set; }

    [Key]
    public int ApplicationRolesApplicationObjectsKey { get; set; }

    [ForeignKey("ApplicationObjectKey")]
    [InverseProperty("System_ApplicationRolesApplicationObjects")]
    public virtual ApplicationObject ApplicationObjectKeyNavigation { get; set; }

    [ForeignKey("ApplicationRoleKey")]
    [InverseProperty("System_ApplicationRolesApplicationObjects")]
    public virtual System_ApplicationRole ApplicationRoleKeyNavigation { get; set; }
}