// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("ApplicationRoles", Schema = "System")]
public partial class System_ApplicationRole
{
    [Key]
    public short ApplicationRoleKey { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string RoleName { get; set; }

    [Required]
    [StringLength(1000)]
    [Unicode(false)]
    public string Description { get; set; }

    public bool IsAdministrator { get; set; }

    public byte SortOrder { get; set; }

    [InverseProperty("ApplicationRoleKeyNavigation")]
    public virtual ICollection<ClientLocationRole> ClientLocationRoles { get; set; } = new List<ClientLocationRole>();

    [InverseProperty("ApplicationRoleKeyNavigation")]
    public virtual ICollection<System_ApplicationRolesApplicationObject> System_ApplicationRolesApplicationObjects { get; set; } = new List<System_ApplicationRolesApplicationObject>();
}