// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[PrimaryKey("BundleId", "LatestVersion")]
[Table("AppVersions", Schema = "System")]
public partial class System_AppVersion
{
    [Key]
    [StringLength(200)]
    [Unicode(false)]
    public string BundleId { get; set; }

    [Key]
    [StringLength(20)]
    [Unicode(false)]
    public string LatestVersion { get; set; }

    public bool ForceStage { get; set; }

    public bool IsEnabled { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RowAdded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeleted { get; set; }
}