// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Table("TicketTypes", Schema = "Ticketing")]
public partial class Ticketing_TicketType
{
    [Key]
    public short TicketTypeKey { get; set; }

    [Required]
    [StringLength(50)]
    public string TicketTypeName { get; set; }

    public bool IsSingleUse { get; set; }

    [Column("UseExternalUUID")]
    public bool UseExternalUuid { get; set; }

    [InverseProperty("TicketTypeKeyNavigation")]
    public virtual ICollection<EntityHierarchy> EntityHierarchies { get; set; } = new List<EntityHierarchy>();
}