// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Additive_DB_Refresh.Models;

[Index("Description", Name = "ix1TransactionTypes")]
public partial class TransactionType
{
    [Key]
    public short TransactionTypeKey { get; set; }

    [Required]
    [StringLength(200)]
    public string Description { get; set; }
}